(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["admin~index"],{

/***/ "./src/components/InformationalBlock.svelte":
/*!**************************************************!*\
  !*** ./src/components/InformationalBlock.svelte ***!
  \**************************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* src\components\InformationalBlock.svelte generated by Svelte v3.32.0 */


const { console: console_1 } = svelte_internal__WEBPACK_IMPORTED_MODULE_0__["globals"];
const file = "src\\components\\InformationalBlock.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-163uqwe-style";
	style.textContent = ".informational-block.svelte-163uqwe{position:relative;max-width:470px;width:100%;height:100%;min-height:809px;padding:20px 20px 20px;background:#ffffff;box-shadow:0px 4px 25px rgba(0, 0, 0, 0.15);border-radius:30px;display:flex;flex-direction:column;justify-content:flex-start;align-items:center;margin-right:30px}.informational-block_type-users-list-table.svelte-163uqwe{min-width:1500px;max-width:initial;border-radius:10px}.informational-block_type-users-list.svelte-163uqwe{border-radius:10px;max-width:487px;max-height:809px;margin-right:40px}.informational-block_type-user-info.svelte-163uqwe{border-radius:5px;margin-right:0;margin-top:30px;max-width:1139px;max-height:821px;min-height:779px}@media screen and (max-width: 1024px){.informational-block.svelte-163uqwe{max-width:100%;margin:0}.accounts-data.svelte-163uqwe{display:none}.personal-data.svelte-163uqwe{display:none}.interactions.svelte-163uqwe{display:none}.active-block.svelte-163uqwe{display:flex}}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiSW5mb3JtYXRpb25hbEJsb2NrLnN2ZWx0ZSIsInNvdXJjZXMiOlsiSW5mb3JtYXRpb25hbEJsb2NrLnN2ZWx0ZSJdLCJzb3VyY2VzQ29udGVudCI6WyI8c2NyaXB0PlxuICBleHBvcnQgbGV0IGNsYXNzZXMgPSBcIlwiO1xuICBleHBvcnQgbGV0IG5hbWU7XG4gIGV4cG9ydCBsZXQgY3VycmVudEluZm9ybWF0aW9uYWxCbG9jaztcbjwvc2NyaXB0PlxuXG48c2VjdGlvblxuICBvbjpzY3JvbGw9eyhlKSA9PiB7XG4gICAgY29uc29sZS5sb2coZSk7XG4gIH19XG4gIGNsYXNzPVwiaW5mb3JtYXRpb25hbC1ibG9jayB7Y2xhc3Nlc31cIlxuICBjbGFzczphY3RpdmUtYmxvY2s9e2N1cnJlbnRJbmZvcm1hdGlvbmFsQmxvY2sgPT09IG5hbWV9XG4+XG4gIDxzbG90IC8+XG48L3NlY3Rpb24+XG5cbjxzdHlsZT5cbiAgLmluZm9ybWF0aW9uYWwtYmxvY2sge1xuICAgIHBvc2l0aW9uOiByZWxhdGl2ZTtcbiAgICBtYXgtd2lkdGg6IDQ3MHB4O1xuICAgIHdpZHRoOiAxMDAlO1xuICAgIGhlaWdodDogMTAwJTtcbiAgICBtaW4taGVpZ2h0OiA4MDlweDtcbiAgICBwYWRkaW5nOiAyMHB4IDIwcHggMjBweDtcbiAgICBiYWNrZ3JvdW5kOiAjZmZmZmZmO1xuICAgIGJveC1zaGFkb3c6IDBweCA0cHggMjVweCByZ2JhKDAsIDAsIDAsIDAuMTUpO1xuICAgIGJvcmRlci1yYWRpdXM6IDMwcHg7XG4gICAgZGlzcGxheTogZmxleDtcbiAgICBmbGV4LWRpcmVjdGlvbjogY29sdW1uO1xuICAgIGp1c3RpZnktY29udGVudDogZmxleC1zdGFydDtcbiAgICBhbGlnbi1pdGVtczogY2VudGVyO1xuICAgIG1hcmdpbi1yaWdodDogMzBweDtcbiAgfVxuXG4gIC5pbmZvcm1hdGlvbmFsLWJsb2NrX3R5cGUtdXNlcnMtbGlzdC10YWJsZSB7XG4gICAgbWluLXdpZHRoOiAxNTAwcHg7XG4gICAgbWF4LXdpZHRoOiBpbml0aWFsO1xuICAgIGJvcmRlci1yYWRpdXM6IDEwcHg7XG4gIH1cbiAgLmluZm9ybWF0aW9uYWwtYmxvY2tfdHlwZS11c2Vycy1saXN0IHtcbiAgICBib3JkZXItcmFkaXVzOiAxMHB4O1xuICAgIG1heC13aWR0aDogNDg3cHg7XG4gICAgbWF4LWhlaWdodDogODA5cHg7XG4gICAgbWFyZ2luLXJpZ2h0OiA0MHB4O1xuICB9XG4gIC5pbmZvcm1hdGlvbmFsLWJsb2NrX3R5cGUtdXNlci1pbmZve1xuICAgIGJvcmRlci1yYWRpdXM6IDVweDtcbiAgICBtYXJnaW4tcmlnaHQ6IDA7XG4gICAgbWFyZ2luLXRvcDogMzBweDtcbiAgICBtYXgtd2lkdGg6IDExMzlweDtcbiAgICBtYXgtaGVpZ2h0OiA4MjFweDtcbiAgICBtaW4taGVpZ2h0OiA3NzlweDtcbiAgfVxuXG5cblxuICBAbWVkaWEgc2NyZWVuIGFuZCAobWF4LXdpZHRoOiAxMDI0cHgpIHtcbiAgICAuaW5mb3JtYXRpb25hbC1ibG9jayB7XG4gICAgICBtYXgtd2lkdGg6IDEwMCU7XG4gICAgICBtYXJnaW46IDA7XG4gICAgfVxuICAgIC5hY2NvdW50cy1kYXRhIHtcbiAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgfVxuICAgIC5wZXJzb25hbC1kYXRhIHtcbiAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgfVxuICAgIC5pbnRlcmFjdGlvbnMge1xuICAgICAgZGlzcGxheTogbm9uZTtcbiAgICB9XG4gICAgLmFjdGl2ZS1ibG9jayB7XG4gICAgICBkaXNwbGF5OiBmbGV4O1xuICAgIH1cbiAgfVxuPC9zdHlsZT5cbiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFpQkUsb0JBQW9CLGVBQUMsQ0FBQyxBQUNwQixRQUFRLENBQUUsUUFBUSxDQUNsQixTQUFTLENBQUUsS0FBSyxDQUNoQixLQUFLLENBQUUsSUFBSSxDQUNYLE1BQU0sQ0FBRSxJQUFJLENBQ1osVUFBVSxDQUFFLEtBQUssQ0FDakIsT0FBTyxDQUFFLElBQUksQ0FBQyxJQUFJLENBQUMsSUFBSSxDQUN2QixVQUFVLENBQUUsT0FBTyxDQUNuQixVQUFVLENBQUUsR0FBRyxDQUFDLEdBQUcsQ0FBQyxJQUFJLENBQUMsS0FBSyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxJQUFJLENBQUMsQ0FDNUMsYUFBYSxDQUFFLElBQUksQ0FDbkIsT0FBTyxDQUFFLElBQUksQ0FDYixjQUFjLENBQUUsTUFBTSxDQUN0QixlQUFlLENBQUUsVUFBVSxDQUMzQixXQUFXLENBQUUsTUFBTSxDQUNuQixZQUFZLENBQUUsSUFBSSxBQUNwQixDQUFDLEFBRUQsMENBQTBDLGVBQUMsQ0FBQyxBQUMxQyxTQUFTLENBQUUsTUFBTSxDQUNqQixTQUFTLENBQUUsT0FBTyxDQUNsQixhQUFhLENBQUUsSUFBSSxBQUNyQixDQUFDLEFBQ0Qsb0NBQW9DLGVBQUMsQ0FBQyxBQUNwQyxhQUFhLENBQUUsSUFBSSxDQUNuQixTQUFTLENBQUUsS0FBSyxDQUNoQixVQUFVLENBQUUsS0FBSyxDQUNqQixZQUFZLENBQUUsSUFBSSxBQUNwQixDQUFDLEFBQ0Qsa0RBQW1DLENBQUMsQUFDbEMsYUFBYSxDQUFFLEdBQUcsQ0FDbEIsWUFBWSxDQUFFLENBQUMsQ0FDZixVQUFVLENBQUUsSUFBSSxDQUNoQixTQUFTLENBQUUsTUFBTSxDQUNqQixVQUFVLENBQUUsS0FBSyxDQUNqQixVQUFVLENBQUUsS0FBSyxBQUNuQixDQUFDLEFBSUQsT0FBTyxNQUFNLENBQUMsR0FBRyxDQUFDLFlBQVksTUFBTSxDQUFDLEFBQUMsQ0FBQyxBQUNyQyxvQkFBb0IsZUFBQyxDQUFDLEFBQ3BCLFNBQVMsQ0FBRSxJQUFJLENBQ2YsTUFBTSxDQUFFLENBQUMsQUFDWCxDQUFDLEFBQ0QsY0FBYyxlQUFDLENBQUMsQUFDZCxPQUFPLENBQUUsSUFBSSxBQUNmLENBQUMsQUFDRCxjQUFjLGVBQUMsQ0FBQyxBQUNkLE9BQU8sQ0FBRSxJQUFJLEFBQ2YsQ0FBQyxBQUNELGFBQWEsZUFBQyxDQUFDLEFBQ2IsT0FBTyxDQUFFLElBQUksQUFDZixDQUFDLEFBQ0QsYUFBYSxlQUFDLENBQUMsQUFDYixPQUFPLENBQUUsSUFBSSxBQUNmLENBQUMsQUFDSCxDQUFDIn0= */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

function create_fragment(ctx) {
	let section;
	let section_class_value;
	let current;
	let mounted;
	let dispose;
	const default_slot_template = /*#slots*/ ctx[4].default;
	const default_slot = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_slot"])(default_slot_template, ctx, /*$$scope*/ ctx[3], null);

	const block = {
		c: function create() {
			section = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("section");
			if (default_slot) default_slot.c();
			this.h();
		},
		l: function claim(nodes) {
			section = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SECTION", { class: true });
			var section_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(section);
			if (default_slot) default_slot.l(section_nodes);
			section_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(section, "class", section_class_value = "informational-block " + /*classes*/ ctx[0] + " svelte-163uqwe");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(section, "active-block", /*currentInformationalBlock*/ ctx[2] === /*name*/ ctx[1]);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(section, file, 6, 0, 106);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, section, anchor);

			if (default_slot) {
				default_slot.m(section, null);
			}

			current = true;

			if (!mounted) {
				dispose = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen_dev"])(section, "scroll", /*scroll_handler*/ ctx[5], false, false, false);
				mounted = true;
			}
		},
		p: function update(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 8) {
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["update_slot"])(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[3], dirty, null, null);
				}
			}

			if (!current || dirty & /*classes*/ 1 && section_class_value !== (section_class_value = "informational-block " + /*classes*/ ctx[0] + " svelte-163uqwe")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(section, "class", section_class_value);
			}

			if (dirty & /*classes, currentInformationalBlock, name*/ 7) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(section, "active-block", /*currentInformationalBlock*/ ctx[2] === /*name*/ ctx[1]);
			}
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(default_slot, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(default_slot, local);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(section);
			if (default_slot) default_slot.d(detaching);
			mounted = false;
			dispose();
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("InformationalBlock", slots, ['default']);
	let { classes = "" } = $$props;
	let { name } = $$props;
	let { currentInformationalBlock } = $$props;
	const writable_props = ["classes", "name", "currentInformationalBlock"];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console_1.warn(`<InformationalBlock> was created with unknown prop '${key}'`);
	});

	const scroll_handler = e => {
		console.log(e);
	};

	$$self.$$set = $$props => {
		if ("classes" in $$props) $$invalidate(0, classes = $$props.classes);
		if ("name" in $$props) $$invalidate(1, name = $$props.name);
		if ("currentInformationalBlock" in $$props) $$invalidate(2, currentInformationalBlock = $$props.currentInformationalBlock);
		if ("$$scope" in $$props) $$invalidate(3, $$scope = $$props.$$scope);
	};

	$$self.$capture_state = () => ({ classes, name, currentInformationalBlock });

	$$self.$inject_state = $$props => {
		if ("classes" in $$props) $$invalidate(0, classes = $$props.classes);
		if ("name" in $$props) $$invalidate(1, name = $$props.name);
		if ("currentInformationalBlock" in $$props) $$invalidate(2, currentInformationalBlock = $$props.currentInformationalBlock);
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	return [classes, name, currentInformationalBlock, $$scope, slots, scroll_handler];
}

class InformationalBlock extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-163uqwe-style")) add_css();

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], {
			classes: 0,
			name: 1,
			currentInformationalBlock: 2
		});

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "InformationalBlock",
			options,
			id: create_fragment.name
		});

		const { ctx } = this.$$;
		const props = options.props || {};

		if (/*name*/ ctx[1] === undefined && !("name" in props)) {
			console_1.warn("<InformationalBlock> was created without expected prop 'name'");
		}

		if (/*currentInformationalBlock*/ ctx[2] === undefined && !("currentInformationalBlock" in props)) {
			console_1.warn("<InformationalBlock> was created without expected prop 'currentInformationalBlock'");
		}
	}

	get classes() {
		throw new Error("<InformationalBlock>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set classes(value) {
		throw new Error("<InformationalBlock>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get name() {
		throw new Error("<InformationalBlock>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set name(value) {
		throw new Error("<InformationalBlock>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get currentInformationalBlock() {
		throw new Error("<InformationalBlock>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set currentInformationalBlock(value) {
		throw new Error("<InformationalBlock>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}
}

/* harmony default export */ __webpack_exports__["default"] = (InformationalBlock);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvY29tcG9uZW50cy9JbmZvcm1hdGlvbmFsQmxvY2suc3ZlbHRlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztpSkFVOEIsR0FBTzsrSEFDZixHQUF5QixpQkFBSyxHQUFJOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Z0lBRDFCLEdBQU87Ozs7O2dJQUNmLEdBQXlCLGlCQUFLLEdBQUk7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7T0FWM0MsT0FBTyxHQUFHLEVBQUU7T0FDWixJQUFJO09BQ0oseUJBQXlCOzs7Ozs7O3dCQUl4QixDQUFDO0VBQ1gsT0FBTyxDQUFDLEdBQUcsQ0FBQyxDQUFDIiwiZmlsZSI6IjA0YTYwMGQyZDAxMWU3ZmZhNWUyL2FkbWlufmluZGV4LmFkbWlufmluZGV4LmpzIiwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgZXhwb3J0IGxldCBjbGFzc2VzID0gXCJcIjtcbiAgZXhwb3J0IGxldCBuYW1lO1xuICBleHBvcnQgbGV0IGN1cnJlbnRJbmZvcm1hdGlvbmFsQmxvY2s7XG48L3NjcmlwdD5cblxuPHNlY3Rpb25cbiAgb246c2Nyb2xsPXsoZSkgPT4ge1xuICAgIGNvbnNvbGUubG9nKGUpO1xuICB9fVxuICBjbGFzcz1cImluZm9ybWF0aW9uYWwtYmxvY2sge2NsYXNzZXN9XCJcbiAgY2xhc3M6YWN0aXZlLWJsb2NrPXtjdXJyZW50SW5mb3JtYXRpb25hbEJsb2NrID09PSBuYW1lfVxuPlxuICA8c2xvdCAvPlxuPC9zZWN0aW9uPlxuXG48c3R5bGU+XG4gIC5pbmZvcm1hdGlvbmFsLWJsb2NrIHtcbiAgICBwb3NpdGlvbjogcmVsYXRpdmU7XG4gICAgbWF4LXdpZHRoOiA0NzBweDtcbiAgICB3aWR0aDogMTAwJTtcbiAgICBoZWlnaHQ6IDEwMCU7XG4gICAgbWluLWhlaWdodDogODA5cHg7XG4gICAgcGFkZGluZzogMjBweCAyMHB4IDIwcHg7XG4gICAgYmFja2dyb3VuZDogI2ZmZmZmZjtcbiAgICBib3gtc2hhZG93OiAwcHggNHB4IDI1cHggcmdiYSgwLCAwLCAwLCAwLjE1KTtcbiAgICBib3JkZXItcmFkaXVzOiAzMHB4O1xuICAgIGRpc3BsYXk6IGZsZXg7XG4gICAgZmxleC1kaXJlY3Rpb246IGNvbHVtbjtcbiAgICBqdXN0aWZ5LWNvbnRlbnQ6IGZsZXgtc3RhcnQ7XG4gICAgYWxpZ24taXRlbXM6IGNlbnRlcjtcbiAgICBtYXJnaW4tcmlnaHQ6IDMwcHg7XG4gIH1cblxuICAuaW5mb3JtYXRpb25hbC1ibG9ja190eXBlLXVzZXJzLWxpc3QtdGFibGUge1xuICAgIG1pbi13aWR0aDogMTUwMHB4O1xuICAgIG1heC13aWR0aDogaW5pdGlhbDtcbiAgICBib3JkZXItcmFkaXVzOiAxMHB4O1xuICB9XG4gIC5pbmZvcm1hdGlvbmFsLWJsb2NrX3R5cGUtdXNlcnMtbGlzdCB7XG4gICAgYm9yZGVyLXJhZGl1czogMTBweDtcbiAgICBtYXgtd2lkdGg6IDQ4N3B4O1xuICAgIG1heC1oZWlnaHQ6IDgwOXB4O1xuICAgIG1hcmdpbi1yaWdodDogNDBweDtcbiAgfVxuICAuaW5mb3JtYXRpb25hbC1ibG9ja190eXBlLXVzZXItaW5mb3tcbiAgICBib3JkZXItcmFkaXVzOiA1cHg7XG4gICAgbWFyZ2luLXJpZ2h0OiAwO1xuICAgIG1hcmdpbi10b3A6IDMwcHg7XG4gICAgbWF4LXdpZHRoOiAxMTM5cHg7XG4gICAgbWF4LWhlaWdodDogODIxcHg7XG4gICAgbWluLWhlaWdodDogNzc5cHg7XG4gIH1cblxuXG5cbiAgQG1lZGlhIHNjcmVlbiBhbmQgKG1heC13aWR0aDogMTAyNHB4KSB7XG4gICAgLmluZm9ybWF0aW9uYWwtYmxvY2sge1xuICAgICAgbWF4LXdpZHRoOiAxMDAlO1xuICAgICAgbWFyZ2luOiAwO1xuICAgIH1cbiAgICAuYWNjb3VudHMtZGF0YSB7XG4gICAgICBkaXNwbGF5OiBub25lO1xuICAgIH1cbiAgICAucGVyc29uYWwtZGF0YSB7XG4gICAgICBkaXNwbGF5OiBub25lO1xuICAgIH1cbiAgICAuaW50ZXJhY3Rpb25zIHtcbiAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgfVxuICAgIC5hY3RpdmUtYmxvY2sge1xuICAgICAgZGlzcGxheTogZmxleDtcbiAgICB9XG4gIH1cbjwvc3R5bGU+XG4iXSwic291cmNlUm9vdCI6IiJ9