(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["login~signin"],{

/***/ "./src/components/DigitCodeInput.svelte":
/*!**********************************************!*\
  !*** ./src/components/DigitCodeInput.svelte ***!
  \**********************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! svelte */ "./node_modules/svelte/index.mjs");
/* src\components\DigitCodeInput.svelte generated by Svelte v3.32.0 */



const file = "src\\components\\DigitCodeInput.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-1wwj3sm-style";
	style.textContent = ".wrapper.svelte-1wwj3sm{display:flex;justify-content:center;align-items:center}.digit-code-input.svelte-1wwj3sm{width:60px;height:60px;border:2px solid #035ba0;border-radius:10px;font-style:normal;font-weight:300;font-size:16px;line-height:17px;outline:none;color:gray;letter-spacing:0.02em;transition:0.15s ease-out;margin-bottom:21px;padding-left:23px;margin-right:20px}.digit-code-input.svelte-1wwj3sm:last-of-type{margin-right:0}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiRGlnaXRDb2RlSW5wdXQuc3ZlbHRlIiwic291cmNlcyI6WyJEaWdpdENvZGVJbnB1dC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cclxuICBpbXBvcnQgeyBjcmVhdGVFdmVudERpc3BhdGNoZXIgfSBmcm9tIFwic3ZlbHRlXCI7XHJcbiAgY29uc3QgZGlzcGF0Y2ggPSBjcmVhdGVFdmVudERpc3BhdGNoZXIoKTtcclxuXHJcbiAgZXhwb3J0IGxldCB2YWx1ZSA9IHsgZmlyc3Q6IFwiXCIsIHNlY29uZDogXCJcIiwgdGhpcmQ6IFwiXCIsIGZvdXI6IFwiXCIgfTtcclxuPC9zY3JpcHQ+XHJcblxyXG48ZGl2IGNsYXNzPVwid3JhcHBlclwiPlxyXG4gIDxpbnB1dFxyXG4gICAgdmFsdWU9e3ZhbHVlLmZpcnN0fVxyXG4gICAgb246aW5wdXQ9eyhlKSA9PiB7XHJcbiAgICAgIHZhbHVlLmZpcnN0ID0gZS50YXJnZXQudmFsdWU7XHJcbiAgICB9fVxyXG4gICAgY2xhc3M9XCJkaWdpdC1jb2RlLWlucHV0XCJcclxuICAgIHBsYWNlaG9sZGVyPVwiKlwiXHJcbiAgICB0eXBlPVwidGV4dFwiXHJcbiAgICBtYXhsZW5ndGg9XCIxXCJcclxuICAvPlxyXG4gIDxpbnB1dFxyXG4gICAgdmFsdWU9e3ZhbHVlLnNlY29uZH1cclxuICAgIG9uOmlucHV0PXsoZSkgPT4ge1xyXG4gICAgICB2YWx1ZS5zZWNvbmQgPSBlLnRhcmdldC52YWx1ZTtcclxuICAgIH19XHJcbiAgICBjbGFzcz1cImRpZ2l0LWNvZGUtaW5wdXRcIlxyXG4gICAgcGxhY2Vob2xkZXI9XCIqXCJcclxuICAgIHR5cGU9XCJ0ZXh0XCJcclxuICAgIG1heGxlbmd0aD1cIjFcIlxyXG4gIC8+XHJcbiAgPGlucHV0XHJcbiAgICB2YWx1ZT17dmFsdWUudGhpcmR9XHJcbiAgICBvbjppbnB1dD17KGUpID0+IHtcclxuICAgICAgdmFsdWUudGhpcmQgPSBlLnRhcmdldC52YWx1ZTtcclxuICAgIH19XHJcbiAgICBjbGFzcz1cImRpZ2l0LWNvZGUtaW5wdXRcIlxyXG4gICAgcGxhY2Vob2xkZXI9XCIqXCJcclxuICAgIHR5cGU9XCJ0ZXh0XCJcclxuICAgIG1heGxlbmd0aD1cIjFcIlxyXG4gIC8+XHJcbiAgPGlucHV0XHJcbiAgICB2YWx1ZT17dmFsdWUuZm91cn1cclxuICAgIG9uOmlucHV0PXsoZSkgPT4ge1xyXG4gICAgICB2YWx1ZS5mb3VyID0gZS50YXJnZXQudmFsdWU7XHJcbiAgICB9fVxyXG4gICAgY2xhc3M9XCJkaWdpdC1jb2RlLWlucHV0XCJcclxuICAgIHBsYWNlaG9sZGVyPVwiKlwiXHJcbiAgICB0eXBlPVwidGV4dFwiXHJcbiAgICBtYXhsZW5ndGg9XCIxXCJcclxuICAvPlxyXG48L2Rpdj5cclxuXHJcbjxzdHlsZT5cclxuICAud3JhcHBlciB7XHJcbiAgICBkaXNwbGF5OiBmbGV4O1xyXG4gICAganVzdGlmeS1jb250ZW50OiBjZW50ZXI7XHJcbiAgICBhbGlnbi1pdGVtczogY2VudGVyO1xyXG4gIH1cclxuXHJcbiAgLmRpZ2l0LWNvZGUtaW5wdXQge1xyXG4gICAgd2lkdGg6IDYwcHg7XHJcbiAgICBoZWlnaHQ6IDYwcHg7XHJcbiAgICBib3JkZXI6IDJweCBzb2xpZCAjMDM1YmEwO1xyXG4gICAgYm9yZGVyLXJhZGl1czogMTBweDtcclxuICAgIGZvbnQtc3R5bGU6IG5vcm1hbDtcclxuICAgIGZvbnQtd2VpZ2h0OiAzMDA7XHJcbiAgICBmb250LXNpemU6IDE2cHg7XHJcbiAgICBsaW5lLWhlaWdodDogMTdweDtcclxuICAgIG91dGxpbmU6IG5vbmU7XHJcbiAgICBjb2xvcjogZ3JheTtcclxuICAgIGxldHRlci1zcGFjaW5nOiAwLjAyZW07XHJcbiAgICB0cmFuc2l0aW9uOiAwLjE1cyBlYXNlLW91dDtcclxuICAgIG1hcmdpbi1ib3R0b206IDIxcHg7XHJcbiAgICBwYWRkaW5nLWxlZnQ6IDIzcHg7XHJcbiAgICBtYXJnaW4tcmlnaHQ6IDIwcHg7XHJcbiAgfVxyXG4gIC5kaWdpdC1jb2RlLWlucHV0Omxhc3Qtb2YtdHlwZSB7XHJcbiAgICBtYXJnaW4tcmlnaHQ6IDA7XHJcbiAgfVxyXG48L3N0eWxlPlxyXG4iXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBbURFLFFBQVEsZUFBQyxDQUFDLEFBQ1IsT0FBTyxDQUFFLElBQUksQ0FDYixlQUFlLENBQUUsTUFBTSxDQUN2QixXQUFXLENBQUUsTUFBTSxBQUNyQixDQUFDLEFBRUQsaUJBQWlCLGVBQUMsQ0FBQyxBQUNqQixLQUFLLENBQUUsSUFBSSxDQUNYLE1BQU0sQ0FBRSxJQUFJLENBQ1osTUFBTSxDQUFFLEdBQUcsQ0FBQyxLQUFLLENBQUMsT0FBTyxDQUN6QixhQUFhLENBQUUsSUFBSSxDQUNuQixVQUFVLENBQUUsTUFBTSxDQUNsQixXQUFXLENBQUUsR0FBRyxDQUNoQixTQUFTLENBQUUsSUFBSSxDQUNmLFdBQVcsQ0FBRSxJQUFJLENBQ2pCLE9BQU8sQ0FBRSxJQUFJLENBQ2IsS0FBSyxDQUFFLElBQUksQ0FDWCxjQUFjLENBQUUsTUFBTSxDQUN0QixVQUFVLENBQUUsS0FBSyxDQUFDLFFBQVEsQ0FDMUIsYUFBYSxDQUFFLElBQUksQ0FDbkIsWUFBWSxDQUFFLElBQUksQ0FDbEIsWUFBWSxDQUFFLElBQUksQUFDcEIsQ0FBQyxBQUNELGdDQUFpQixhQUFhLEFBQUMsQ0FBQyxBQUM5QixZQUFZLENBQUUsQ0FBQyxBQUNqQixDQUFDIn0= */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

function create_fragment(ctx) {
	let div;
	let input0;
	let input0_value_value;
	let t0;
	let input1;
	let input1_value_value;
	let t1;
	let input2;
	let input2_value_value;
	let t2;
	let input3;
	let input3_value_value;
	let mounted;
	let dispose;

	const block = {
		c: function create() {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			input0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("input");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			input1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("input");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			input2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("input");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			input3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("input");
			this.h();
		},
		l: function claim(nodes) {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true });
			var div_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div);

			input0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div_nodes, "INPUT", {
				value: true,
				class: true,
				placeholder: true,
				type: true,
				maxlength: true
			});

			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div_nodes);

			input1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div_nodes, "INPUT", {
				value: true,
				class: true,
				placeholder: true,
				type: true,
				maxlength: true
			});

			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div_nodes);

			input2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div_nodes, "INPUT", {
				value: true,
				class: true,
				placeholder: true,
				type: true,
				maxlength: true
			});

			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div_nodes);

			input3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div_nodes, "INPUT", {
				value: true,
				class: true,
				placeholder: true,
				type: true,
				maxlength: true
			});

			div_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			input0.value = input0_value_value = /*value*/ ctx[0].first;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input0, "class", "digit-code-input svelte-1wwj3sm");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input0, "placeholder", "*");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input0, "type", "text");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input0, "maxlength", "1");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(input0, file, 8, 2, 216);
			input1.value = input1_value_value = /*value*/ ctx[0].second;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input1, "class", "digit-code-input svelte-1wwj3sm");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input1, "placeholder", "*");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input1, "type", "text");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input1, "maxlength", "1");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(input1, file, 18, 2, 413);
			input2.value = input2_value_value = /*value*/ ctx[0].third;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input2, "class", "digit-code-input svelte-1wwj3sm");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input2, "placeholder", "*");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input2, "type", "text");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input2, "maxlength", "1");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(input2, file, 28, 2, 612);
			input3.value = input3_value_value = /*value*/ ctx[0].four;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input3, "class", "digit-code-input svelte-1wwj3sm");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input3, "placeholder", "*");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input3, "type", "text");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input3, "maxlength", "1");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(input3, file, 38, 2, 809);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div, "class", "wrapper svelte-1wwj3sm");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div, file, 7, 0, 191);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div, input0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div, input1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div, input2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div, input3);

			if (!mounted) {
				dispose = [
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen_dev"])(input0, "input", /*input_handler*/ ctx[1], false, false, false),
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen_dev"])(input1, "input", /*input_handler_1*/ ctx[2], false, false, false),
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen_dev"])(input2, "input", /*input_handler_2*/ ctx[3], false, false, false),
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen_dev"])(input3, "input", /*input_handler_3*/ ctx[4], false, false, false)
				];

				mounted = true;
			}
		},
		p: function update(ctx, [dirty]) {
			if (dirty & /*value*/ 1 && input0_value_value !== (input0_value_value = /*value*/ ctx[0].first) && input0.value !== input0_value_value) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["prop_dev"])(input0, "value", input0_value_value);
			}

			if (dirty & /*value*/ 1 && input1_value_value !== (input1_value_value = /*value*/ ctx[0].second) && input1.value !== input1_value_value) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["prop_dev"])(input1, "value", input1_value_value);
			}

			if (dirty & /*value*/ 1 && input2_value_value !== (input2_value_value = /*value*/ ctx[0].third) && input2.value !== input2_value_value) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["prop_dev"])(input2, "value", input2_value_value);
			}

			if (dirty & /*value*/ 1 && input3_value_value !== (input3_value_value = /*value*/ ctx[0].four) && input3.value !== input3_value_value) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["prop_dev"])(input3, "value", input3_value_value);
			}
		},
		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div);
			mounted = false;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["run_all"])(dispose);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("DigitCodeInput", slots, []);
	const dispatch = Object(svelte__WEBPACK_IMPORTED_MODULE_1__["createEventDispatcher"])();

	let { value = {
		first: "",
		second: "",
		third: "",
		four: ""
	} } = $$props;

	const writable_props = ["value"];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console.warn(`<DigitCodeInput> was created with unknown prop '${key}'`);
	});

	const input_handler = e => {
		$$invalidate(0, value.first = e.target.value, value);
	};

	const input_handler_1 = e => {
		$$invalidate(0, value.second = e.target.value, value);
	};

	const input_handler_2 = e => {
		$$invalidate(0, value.third = e.target.value, value);
	};

	const input_handler_3 = e => {
		$$invalidate(0, value.four = e.target.value, value);
	};

	$$self.$$set = $$props => {
		if ("value" in $$props) $$invalidate(0, value = $$props.value);
	};

	$$self.$capture_state = () => ({ createEventDispatcher: svelte__WEBPACK_IMPORTED_MODULE_1__["createEventDispatcher"], dispatch, value });

	$$self.$inject_state = $$props => {
		if ("value" in $$props) $$invalidate(0, value = $$props.value);
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	return [value, input_handler, input_handler_1, input_handler_2, input_handler_3];
}

class DigitCodeInput extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-1wwj3sm-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], { value: 0 });

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "DigitCodeInput",
			options,
			id: create_fragment.name
		});
	}

	get value() {
		throw new Error("<DigitCodeInput>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set value(value) {
		throw new Error("<DigitCodeInput>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}
}

/* harmony default export */ __webpack_exports__["default"] = (DigitCodeInput);

/***/ }),

/***/ "./src/components/LoginForm.svelte":
/*!*****************************************!*\
  !*** ./src/components/LoginForm.svelte ***!
  \*****************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var _api_api__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../api/api */ "./src/api/api.js");
/* harmony import */ var _Button_svelte__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ./Button.svelte */ "./src/components/Button.svelte");
/* harmony import */ var _utils_validator__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ../utils/validator */ "./src/utils/validator.js");
/* harmony import */ var _utils_validationState__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! ../utils/validationState */ "./src/utils/validationState.js");
/* harmony import */ var svelte__WEBPACK_IMPORTED_MODULE_5__ = __webpack_require__(/*! svelte */ "./node_modules/svelte/index.mjs");
/* harmony import */ var _sapper_app__WEBPACK_IMPORTED_MODULE_6__ = __webpack_require__(/*! @sapper/app */ "./src/node_modules/@sapper/app.mjs");
/* harmony import */ var _InputField_svelte__WEBPACK_IMPORTED_MODULE_7__ = __webpack_require__(/*! ./InputField.svelte */ "./src/components/InputField.svelte");
/* src\components\LoginForm.svelte generated by Svelte v3.32.0 */


const { Error: Error_1, console: console_1 } = svelte_internal__WEBPACK_IMPORTED_MODULE_0__["globals"];









const file = "src\\components\\LoginForm.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-gqgwot-style";
	style.textContent = ".login-form.svelte-gqgwot{margin:140px 0 0 0}.d-pr-confirm-label.svelte-gqgwot{margin:0 0 0 13px;font-style:normal;font-weight:300;font-size:12px;line-height:13px}@media screen and (max-width: 720px){.login-form.svelte-gqgwot{margin:40px 0 0 0}}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiTG9naW5Gb3JtLnN2ZWx0ZSIsInNvdXJjZXMiOlsiTG9naW5Gb3JtLnN2ZWx0ZSJdLCJzb3VyY2VzQ29udGVudCI6WyI8c2NyaXB0PlxuICBpbXBvcnQge1xuICAgIGxvZ2luRW1haWwsXG4gICAgbG9naW5MaWJyYXJ5Q2FyZCxcbiAgICBzaWduaW4sXG4gICAgc2lnbmluTGlicmFyeUNhcmQsXG4gIH0gZnJvbSBcIi4uL2FwaS9hcGlcIjtcbiAgaW1wb3J0IEJ1dHRvbiBmcm9tIFwiLi9CdXR0b24uc3ZlbHRlXCI7XG4gIGltcG9ydCB7IHZhbGlkYXRvciB9IGZyb20gXCIuLi91dGlscy92YWxpZGF0b3JcIjtcbiAgaW1wb3J0IHsgdmFsaWRhdGlvblN0YXRlIH0gZnJvbSBcIi4uL3V0aWxzL3ZhbGlkYXRpb25TdGF0ZVwiO1xuICBpbXBvcnQgeyBhZnRlclVwZGF0ZSwgb25EZXN0cm95IH0gZnJvbSBcInN2ZWx0ZVwiO1xuICBpbXBvcnQgeyBnb3RvIH0gZnJvbSBcIkBzYXBwZXIvYXBwXCI7XG4gIGltcG9ydCBJbnB1dEZpZWxkIGZyb20gXCIuL0lucHV0RmllbGQuc3ZlbHRlXCI7XG5cbiAgZXhwb3J0IGxldCB0eXBlT2ZMb2dpbjtcbiAgZXhwb3J0IGxldCBlcnJvcjtcbiAgZXhwb3J0IGxldCBzaWduSW4gPSBmYWxzZTtcbiAgLy9jb25zb2xlLmxvZyh2YWxpZGF0aW9uU3RhdGUpO1xuXG4gIFxuICBjb25zdCBSRURJUkVDVF9VUkxfVE9fU0FWRV9UT0tFTl9FWlBST1hZID1cbiAgICBcImh0dHA6Ly9jbGllbnQuZ3BudGJzaWIucnU6MzAwMi9zYXZldG9rZW4/dG9rZW49XCI7XG5cbiAgY29uc3QgdXNlckRhdGEgPSB7XG4gICAgZW1haWw6IFwiXCIsXG4gICAgbGlicmFyeUNhcmROdW1iZXI6IFwiXCIsXG4gICAgcGFzc3dvcmQ6IFwiXCIsXG4gIH07XG4gIGxldCBpc1JlZ0J1dHRvbkFjdGl2ZSA9IGZhbHNlO1xuICBsZXQgY29uZmlybWF0aW9uO1xuXG4gIGxldCBjdXJyZW50VmFsaWRhdGlvblN0YXRlID0gdmFsaWRhdGlvblN0YXRlO1xuXG4gIGFzeW5jIGZ1bmN0aW9uIGhhbmRsZVN1Ym1pdCgpIHtcbiAgICB0cnkge1xuICAgICAgaWYgKHR5cGVPZkxvZ2luID09IFwiZW1haWxcIikge1xuICAgICAgICBsZXQgcmVzID0gYXdhaXQgbG9naW5FbWFpbCh7XG4gICAgICAgICAgZW1haWw6IHVzZXJEYXRhLmVtYWlsLFxuICAgICAgICAgIHBhc3N3b3JkOiB1c2VyRGF0YS5wYXNzd29yZCxcbiAgICAgICAgfSk7XG4gICAgICAgIGlmIChzaWduSW4pIHtcbiAgICAgICAgICBpZiAocmVzID09IFwiV3JvbmcgcGFzc3dvcmRcIiB8fCAhcmVzKSB7XG4gICAgICAgICAgICB0aHJvdyBuZXcgRXJyb3IocmVzKTtcbiAgICAgICAgICB9XG4gICAgICAgICAgbGV0IHVybCA9IFJFRElSRUNUX1VSTF9UT19TQVZFX1RPS0VOX0VaUFJPWFkgKyByZXMudG9rZW47XG4gICAgICAgICAgZ290byh1cmwpO1xuICAgICAgICB9IGVsc2Uge1xuICAgICAgICAgIGdvdG8oXCIvXCIpO1xuICAgICAgICB9XG4gICAgICB9XG4gICAgICBpZiAodHlwZU9mTG9naW4gPT0gXCJsaWJyYXJ5LWNhcmRcIikge1xuICAgICAgICBjb25zb2xlLmxvZyh7XG4gICAgICAgICAgbGlicmFyeUNhcmROdW1iZXI6IHVzZXJEYXRhLmxpYnJhcnlDYXJkTnVtYmVyLFxuICAgICAgICAgIHBhc3N3b3JkOiB1c2VyRGF0YS5wYXNzd29yZCxcbiAgICAgICAgfSk7XG4gICAgICAgIGxldCByZXMgPSBhd2FpdCBsb2dpbkxpYnJhcnlDYXJkKHtcbiAgICAgICAgICBsaWJyYXJ5Q2FyZE51bWJlcjogdXNlckRhdGEubGlicmFyeUNhcmROdW1iZXIsXG4gICAgICAgICAgcGFzc3dvcmQ6IHVzZXJEYXRhLnBhc3N3b3JkLFxuICAgICAgICB9KTtcbiAgICAgICAgaWYgKHNpZ25Jbikge1xuICAgICAgICAgIGlmIChyZXMgPT0gXCJXcm9uZyBwYXNzd29yZFwiIHx8ICFyZXMpIHtcbiAgICAgICAgICAgIHRocm93IG5ldyBFcnJvcihyZXMpO1xuICAgICAgICAgIH1cbiAgICAgICAgICBsZXQgdXJsID0gUkVESVJFQ1RfVVJMX1RPX1NBVkVfVE9LRU5fRVpQUk9YWSArIHJlcy50b2tlbjtcbiAgICAgICAgICBnb3RvKHVybCk7XG4gICAgICAgIH0gZWxzZSB7XG4gICAgICAgICAgZ290byhcIi9cIik7XG4gICAgICAgIH1cbiAgICAgIH1cbiAgICB9IGNhdGNoIChlKSB7XG4gICAgICBlcnJvciA9IFwi0J3QtdC/0YDQsNCy0LjQu9GM0L3Ri9C1INC/0L7Rh9GC0LAg0LjQu9C4INC/0LDRgNC+0LvRjFwiO1xuICAgICAgY29uc29sZS5sb2coZSk7XG4gICAgICBcbiAgICB9XG4gIH1cbiAgZnVuY3Rpb24gdXBkYXRlSW5wdXRzKG5vZGUsIGJhcikge1xuICAgIGNsZWFySW5wdXQoKTtcbiAgICByZXR1cm4ge1xuICAgICAgdXBkYXRlKGJhcikge1xuICAgICAgICBjbGVhcklucHV0KCk7XG4gICAgICB9LFxuICAgIH07XG4gIH1cbiAgZnVuY3Rpb24gY2xlYXJJbnB1dCgpIHtcbiAgICBmb3IgKGxldCBwcm9wIGluIHVzZXJEYXRhKSB7XG4gICAgICB1c2VyRGF0YVtwcm9wXSA9IFwiXCI7XG4gICAgfVxuICAgIGZvciAobGV0IHByb3AgaW4gY3VycmVudFZhbGlkYXRpb25TdGF0ZSkge1xuICAgICAgY3VycmVudFZhbGlkYXRpb25TdGF0ZVtwcm9wXSA9IHsgc3RhdGU6IHRydWUsIG1lc3NhZ2U6IG51bGwgfTtcbiAgICB9XG4gIH1cblxuICBjb25zb2xlLmxvZyh0eXBlb2YgY2xlYXJJbnB1dCk7XG4gIGFmdGVyVXBkYXRlKCgpID0+IHtcbiAgICBmb3IgKGxldCBpIGluIGN1cnJlbnRWYWxpZGF0aW9uU3RhdGUpIHtcbiAgICAgIGlmICghY3VycmVudFZhbGlkYXRpb25TdGF0ZVtpXS5zdGF0ZSkge1xuICAgICAgICBpc1JlZ0J1dHRvbkFjdGl2ZSA9IGZhbHNlO1xuICAgICAgICByZXR1cm47XG4gICAgICB9XG4gICAgICBpc1JlZ0J1dHRvbkFjdGl2ZSA9IHRydWU7XG4gICAgfVxuXG4gICAgLyogZm9yIChsZXQgaSBpbiB1c2VyRGF0YSkge1xuICAgICAgaWYgKCF1c2VyRGF0YVtpXSkge1xuICAgICAgICBpc1JlZ0J1dHRvbkFjdGl2ZSA9IGZhbHNlO1xuICAgICAgICByZXR1cm47XG4gICAgICB9XG4gICAgICBpc1JlZ0J1dHRvbkFjdGl2ZSA9IHRydWU7XG4gICAgfSovXG5cbiAgICAvL2NvbnNvbGUubG9nKHZhbGlkYXRpb25TdGF0ZSk7XG4gIH0pO1xuICBvbkRlc3Ryb3koKCkgPT4ge1xuICAgIGNsZWFySW5wdXQoKTtcbiAgfSk7XG48L3NjcmlwdD5cblxuPGZvcm1cbiAgdXNlOnVwZGF0ZUlucHV0cz17dHlwZU9mTG9naW59XG4gIG9uOnN1Ym1pdHxwcmV2ZW50RGVmYXVsdD17aGFuZGxlU3VibWl0fVxuICBjbGFzcz1cInRleHQtbGVmdCBkLWZsZXggZmxleC1jb2x1bW4gYWxpZ24taXRlbXMtY2VudGVyIGxvZ2luLWZvcm1cIlxuPlxuICB7I2lmIHR5cGVPZkxvZ2luID09IFwiZW1haWxcIn1cbiAgICA8SW5wdXRGaWVsZFxuICAgICAgYmluZDp1c2VyZGF0YT17dXNlckRhdGEuZW1haWx9XG4gICAgICB2YWxpZGF0aW9uPXtmYWxzZX1cbiAgICAgIHtlcnJvcn1cbiAgICAgIGlkPVwiaW5wdXRFbWFpbFwiXG4gICAgICBuYW1lPVwiaW5wdXRFbWFpbFwiXG4gICAgICB0eXBlPVwiZW1haWxcIlxuICAgICAge2N1cnJlbnRWYWxpZGF0aW9uU3RhdGV9XG4gICAgICBsYWJlbFRleHQ9XCJFbWFpbFwiXG4gICAgLz5cbiAgey9pZn1cbiAgeyNpZiB0eXBlT2ZMb2dpbiA9PSBcImxpYnJhcnktY2FyZFwifVxuICAgIDxJbnB1dEZpZWxkXG4gICAgICBiaW5kOnVzZXJkYXRhPXt1c2VyRGF0YS5saWJyYXJ5Q2FyZE51bWJlcn1cbiAgICAgIHZhbGlkYXRpb249e2ZhbHNlfVxuICAgICAge2Vycm9yfVxuICAgICAgaWQ9XCJpbnB1dExpYnJhcnlDYXJkXCJcbiAgICAgIG5hbWU9XCJpbnB1dExpYnJhcnlDYXJkXCJcbiAgICAgIHR5cGU9XCJ0ZXh0XCJcbiAgICAgIHtjdXJyZW50VmFsaWRhdGlvblN0YXRlfVxuICAgICAgbGFiZWxUZXh0PVwi0J3QvtC80LXRgCDRh9C40YLQsNGC0LXQu9GM0YHQutC+0LPQviDQsdC40LvQtdGC0LBcIlxuICAgIC8+XG4gIHsvaWZ9XG5cbiAgPElucHV0RmllbGRcbiAgICBiaW5kOnVzZXJkYXRhPXt1c2VyRGF0YS5wYXNzd29yZH1cbiAgICBvbjpyZXNldFxuICAgIHZhbGlkYXRpb249e2ZhbHNlfVxuICAgIGlkPVwiaW5wdXRQYXNzd29yZFwiXG4gICAgcmVzZXRQYXNzd29yZD1cInt0cnVlfTtcIlxuICAgIHBhc3N3b3JkPXt0cnVlfVxuICAgIG5hbWU9XCJpbnB1dFBhc3N3b3JkXCJcbiAgICB0eXBlPVwicGFzc3dvcmRcIlxuICAgIHtjdXJyZW50VmFsaWRhdGlvblN0YXRlfVxuICAgIGxhYmVsVGV4dD1cItCf0LDRgNC+0LvRjFwiXG4gIC8+XG4gIDxkaXYgY2xhc3M9XCJkLWZsZXggZmxleC1yb3cganVzdGlmeS1jb250ZW50LWNlbnRlciBhbGlnbi1pdGVtcy1jZW50ZXJcIj5cbiAgICA8aW5wdXRcbiAgICAgIGNsYXNzPVwiXCJcbiAgICAgIGlkPVwiY29uZmlybWF0aW9uXCJcbiAgICAgIHR5cGU9XCJjaGVja2JveFwiXG4gICAgICBiaW5kOmNoZWNrZWQ9e2NvbmZpcm1hdGlvbn1cbiAgICAgIG9uOmNoYW5nZT17Y29uc29sZS5sb2coY29uZmlybWF0aW9uKX1cbiAgICAvPlxuICAgIDxsYWJlbCBjbGFzcz1cImQtcHItY29uZmlybS1sYWJlbFwiIGZvcj1cImNvbmZpcm1hdGlvblwiPlxuICAgICAg0JfQsNC/0L7QvNC90LjRgtGMINC80LXQvdGPXG4gICAgPC9sYWJlbD5cbiAgPC9kaXY+XG4gIDxCdXR0b25cbiAgICBkaXNhYmxlZD17IWlzUmVnQnV0dG9uQWN0aXZlfVxuICAgIHR5cGU9XCJzdWJtaXRcIlxuICAgIGNvbnRlbnQ9e1wi0JLQvtC50YLQuFwifVxuICAgIGNsYXNzZXM9e1wibS1idXR0b25fbWFyZ2luLWJvdHRvbVwifVxuICAvPlxuICA8IS0tPGJ1dHRvbiBvbjpjbGljaz17Y2xlYXJJbnB1dH0gY2xhc3M9XCJjbGVhci1idXR0b25cIiB0eXBlPVwiYnV0dG9uXCJcbiAgICA+0KHQsdGA0L7RgdC40YLRjCDQstGB0LU8L2J1dHRvblxuICA+LS0+XG48L2Zvcm0+XG5cbjxzdHlsZT5cbiAgLmxvZ2luLWZvcm0ge1xuICAgIG1hcmdpbjogMTQwcHggMCAwIDA7XG4gIH1cblxuICAubS1idXR0b24ge1xuICAgIGJvcmRlcjogbm9uZTtcbiAgICBjb2xvcjogd2hpdGU7XG4gICAgd2lkdGg6IDIwMHB4O1xuICAgIGhlaWdodDogNDBweDtcbiAgICBiYWNrZ3JvdW5kLWNvbG9yOiAjMDM1YmEwO1xuICAgIGJvcmRlci1yYWRpdXM6IDEwcHg7XG4gICAgZm9udC1zdHlsZTogbm9ybWFsO1xuICAgIGZvbnQtd2VpZ2h0OiBib2xkO1xuICAgIGZvbnQtc2l6ZTogMjBweDtcbiAgICBsaW5lLWhlaWdodDogMjJweDtcbiAgfVxuXG4gIC5sb2ctYnV0dG9uOmRpc2FibGVkIHtcbiAgICBiYWNrZ3JvdW5kLWNvbG9yOiBncmF5O1xuICB9XG4gIC5sb2ctYnV0dG9uIHtcbiAgICBtYXJnaW4tdG9wOiAzNnB4O1xuICB9XG5cbiAgLmNsZWFyLWJ1dHRvbiB7XG4gICAgYm9yZGVyOiBub25lO1xuICAgIHBvc2l0aW9uOiBhYnNvbHV0ZTtcbiAgICBib3R0b206IDIwcHg7XG4gICAgcmlnaHQ6IDIwcHg7XG4gICAgZm9udC1zdHlsZTogbm9ybWFsO1xuICAgIGZvbnQtd2VpZ2h0OiAzMDA7XG4gICAgZm9udC1zaXplOiAxMnB4O1xuICAgIGxpbmUtaGVpZ2h0OiAxM3B4O1xuICAgIHRleHQtYWxpZ246IGNlbnRlcjtcbiAgICBsZXR0ZXItc3BhY2luZzogMC4wMmVtO1xuICAgIGJhY2tncm91bmQtY29sb3I6IHRyYW5zcGFyZW50O1xuICB9XG5cbiAgLmQtcHItY29uZmlybS1sYWJlbCB7XG4gICAgbWFyZ2luOiAwIDAgMCAxM3B4O1xuICAgIGZvbnQtc3R5bGU6IG5vcm1hbDtcbiAgICBmb250LXdlaWdodDogMzAwO1xuICAgIGZvbnQtc2l6ZTogMTJweDtcbiAgICBsaW5lLWhlaWdodDogMTNweDtcbiAgfVxuXG4gIEBtZWRpYSBzY3JlZW4gYW5kIChtYXgtd2lkdGg6IDcyMHB4KSB7XG4gICAgLmxvZ2luLWZvcm0ge1xuICAgICAgbWFyZ2luOiA0MHB4IDAgMCAwO1xuICAgIH1cbiAgfVxuPC9zdHlsZT5cbiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUF1TEUsV0FBVyxjQUFDLENBQUMsQUFDWCxNQUFNLENBQUUsS0FBSyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxBQUNyQixDQUFDLEFBb0NELG1CQUFtQixjQUFDLENBQUMsQUFDbkIsTUFBTSxDQUFFLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLElBQUksQ0FDbEIsVUFBVSxDQUFFLE1BQU0sQ0FDbEIsV0FBVyxDQUFFLEdBQUcsQ0FDaEIsU0FBUyxDQUFFLElBQUksQ0FDZixXQUFXLENBQUUsSUFBSSxBQUNuQixDQUFDLEFBRUQsT0FBTyxNQUFNLENBQUMsR0FBRyxDQUFDLFlBQVksS0FBSyxDQUFDLEFBQUMsQ0FBQyxBQUNwQyxXQUFXLGNBQUMsQ0FBQyxBQUNYLE1BQU0sQ0FBRSxJQUFJLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLEFBQ3BCLENBQUMsQUFDSCxDQUFDIn0= */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

// (123:2) {#if typeOfLogin == "email"}
function create_if_block_1(ctx) {
	let inputfield;
	let updating_userdata;
	let current;

	function inputfield_userdata_binding(value) {
		/*inputfield_userdata_binding*/ ctx[9].call(null, value);
	}

	let inputfield_props = {
		validation: false,
		error: /*error*/ ctx[0],
		id: "inputEmail",
		name: "inputEmail",
		type: "email",
		currentValidationState: /*currentValidationState*/ ctx[5],
		labelText: "Email"
	};

	if (/*userData*/ ctx[2].email !== void 0) {
		inputfield_props.userdata = /*userData*/ ctx[2].email;
	}

	inputfield = new _InputField_svelte__WEBPACK_IMPORTED_MODULE_7__["default"]({ props: inputfield_props, $$inline: true });
	svelte_internal__WEBPACK_IMPORTED_MODULE_0__["binding_callbacks"].push(() => Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["bind"])(inputfield, "userdata", inputfield_userdata_binding));

	const block = {
		c: function create() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(inputfield.$$.fragment);
		},
		l: function claim(nodes) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(inputfield.$$.fragment, nodes);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(inputfield, target, anchor);
			current = true;
		},
		p: function update(ctx, dirty) {
			const inputfield_changes = {};
			if (dirty & /*error*/ 1) inputfield_changes.error = /*error*/ ctx[0];
			if (dirty & /*currentValidationState*/ 32) inputfield_changes.currentValidationState = /*currentValidationState*/ ctx[5];

			if (!updating_userdata && dirty & /*userData*/ 4) {
				updating_userdata = true;
				inputfield_changes.userdata = /*userData*/ ctx[2].email;
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_flush_callback"])(() => updating_userdata = false);
			}

			inputfield.$set(inputfield_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(inputfield.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(inputfield.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(inputfield, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_if_block_1.name,
		type: "if",
		source: "(123:2) {#if typeOfLogin == \\\"email\\\"}",
		ctx
	});

	return block;
}

// (135:2) {#if typeOfLogin == "library-card"}
function create_if_block(ctx) {
	let inputfield;
	let updating_userdata;
	let current;

	function inputfield_userdata_binding_1(value) {
		/*inputfield_userdata_binding_1*/ ctx[10].call(null, value);
	}

	let inputfield_props = {
		validation: false,
		error: /*error*/ ctx[0],
		id: "inputLibraryCard",
		name: "inputLibraryCard",
		type: "text",
		currentValidationState: /*currentValidationState*/ ctx[5],
		labelText: "Номер читательского билета"
	};

	if (/*userData*/ ctx[2].libraryCardNumber !== void 0) {
		inputfield_props.userdata = /*userData*/ ctx[2].libraryCardNumber;
	}

	inputfield = new _InputField_svelte__WEBPACK_IMPORTED_MODULE_7__["default"]({ props: inputfield_props, $$inline: true });
	svelte_internal__WEBPACK_IMPORTED_MODULE_0__["binding_callbacks"].push(() => Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["bind"])(inputfield, "userdata", inputfield_userdata_binding_1));

	const block = {
		c: function create() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(inputfield.$$.fragment);
		},
		l: function claim(nodes) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(inputfield.$$.fragment, nodes);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(inputfield, target, anchor);
			current = true;
		},
		p: function update(ctx, dirty) {
			const inputfield_changes = {};
			if (dirty & /*error*/ 1) inputfield_changes.error = /*error*/ ctx[0];
			if (dirty & /*currentValidationState*/ 32) inputfield_changes.currentValidationState = /*currentValidationState*/ ctx[5];

			if (!updating_userdata && dirty & /*userData*/ 4) {
				updating_userdata = true;
				inputfield_changes.userdata = /*userData*/ ctx[2].libraryCardNumber;
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_flush_callback"])(() => updating_userdata = false);
			}

			inputfield.$set(inputfield_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(inputfield.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(inputfield.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(inputfield, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_if_block.name,
		type: "if",
		source: "(135:2) {#if typeOfLogin == \\\"library-card\\\"}",
		ctx
	});

	return block;
}

function create_fragment(ctx) {
	let form;
	let t0;
	let t1;
	let inputfield;
	let updating_userdata;
	let t2;
	let div;
	let input;
	let t3;
	let label;
	let t4;
	let t5;
	let button;
	let updateInputs_action;
	let current;
	let mounted;
	let dispose;
	let if_block0 = /*typeOfLogin*/ ctx[1] == "email" && create_if_block_1(ctx);
	let if_block1 = /*typeOfLogin*/ ctx[1] == "library-card" && create_if_block(ctx);

	function inputfield_userdata_binding_2(value) {
		/*inputfield_userdata_binding_2*/ ctx[11].call(null, value);
	}

	let inputfield_props = {
		validation: false,
		id: "inputPassword",
		resetPassword: "" + (true + ";"),
		password: true,
		name: "inputPassword",
		type: "password",
		currentValidationState: /*currentValidationState*/ ctx[5],
		labelText: "Пароль"
	};

	if (/*userData*/ ctx[2].password !== void 0) {
		inputfield_props.userdata = /*userData*/ ctx[2].password;
	}

	inputfield = new _InputField_svelte__WEBPACK_IMPORTED_MODULE_7__["default"]({ props: inputfield_props, $$inline: true });
	svelte_internal__WEBPACK_IMPORTED_MODULE_0__["binding_callbacks"].push(() => Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["bind"])(inputfield, "userdata", inputfield_userdata_binding_2));
	inputfield.$on("reset", /*reset_handler*/ ctx[12]);

	button = new _Button_svelte__WEBPACK_IMPORTED_MODULE_2__["default"]({
			props: {
				disabled: !/*isRegButtonActive*/ ctx[3],
				type: "submit",
				content: "Войти",
				classes: "m-button_margin-bottom"
			},
			$$inline: true
		});

	const block = {
		c: function create() {
			form = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("form");
			if (if_block0) if_block0.c();
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			if (if_block1) if_block1.c();
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(inputfield.$$.fragment);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			input = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("input");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			label = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("label");
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Запомнить меня");
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(button.$$.fragment);
			this.h();
		},
		l: function claim(nodes) {
			form = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "FORM", { class: true });
			var form_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(form);
			if (if_block0) if_block0.l(form_nodes);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(form_nodes);
			if (if_block1) if_block1.l(form_nodes);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(form_nodes);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(inputfield.$$.fragment, form_nodes);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(form_nodes);
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(form_nodes, "DIV", { class: true });
			var div_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div);
			input = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div_nodes, "INPUT", { class: true, id: true, type: true });
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div_nodes);
			label = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div_nodes, "LABEL", { class: true, for: true });
			var label_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(label);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(label_nodes, "Запомнить меня");
			label_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(form_nodes);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(button.$$.fragment, form_nodes);
			form_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input, "class", "");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input, "id", "confirmation");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input, "type", "checkbox");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(input, file, 160, 4, 3870);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(label, "class", "d-pr-confirm-label svelte-gqgwot");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(label, "for", "confirmation");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(label, file, 167, 4, 4027);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div, "class", "d-flex flex-row justify-content-center align-items-center");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div, file, 159, 2, 3794);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(form, "class", "text-left d-flex flex-column align-items-center login-form svelte-gqgwot");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(form, file, 117, 0, 2811);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, form, anchor);
			if (if_block0) if_block0.m(form, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(form, t0);
			if (if_block1) if_block1.m(form, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(form, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(inputfield, form, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(form, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(form, div);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div, input);
			input.checked = /*confirmation*/ ctx[4];
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div, label);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(label, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(form, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(button, form, null);
			current = true;

			if (!mounted) {
				dispose = [
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen_dev"])(input, "change", /*input_change_handler*/ ctx[13]),
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen_dev"])(
						input,
						"change",
						function () {
							if (Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["is_function"])(console.log(/*confirmation*/ ctx[4]))) console.log(/*confirmation*/ ctx[4]).apply(this, arguments);
						},
						false,
						false,
						false
					),
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["action_destroyer"])(updateInputs_action = /*updateInputs*/ ctx[7].call(null, form, /*typeOfLogin*/ ctx[1])),
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen_dev"])(form, "submit", Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["prevent_default"])(/*handleSubmit*/ ctx[6]), false, true, false)
				];

				mounted = true;
			}
		},
		p: function update(new_ctx, [dirty]) {
			ctx = new_ctx;

			if (/*typeOfLogin*/ ctx[1] == "email") {
				if (if_block0) {
					if_block0.p(ctx, dirty);

					if (dirty & /*typeOfLogin*/ 2) {
						Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block0, 1);
					}
				} else {
					if_block0 = create_if_block_1(ctx);
					if_block0.c();
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block0, 1);
					if_block0.m(form, t0);
				}
			} else if (if_block0) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["group_outros"])();

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_block0, 1, 1, () => {
					if_block0 = null;
				});

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["check_outros"])();
			}

			if (/*typeOfLogin*/ ctx[1] == "library-card") {
				if (if_block1) {
					if_block1.p(ctx, dirty);

					if (dirty & /*typeOfLogin*/ 2) {
						Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block1, 1);
					}
				} else {
					if_block1 = create_if_block(ctx);
					if_block1.c();
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block1, 1);
					if_block1.m(form, t1);
				}
			} else if (if_block1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["group_outros"])();

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_block1, 1, 1, () => {
					if_block1 = null;
				});

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["check_outros"])();
			}

			const inputfield_changes = {};
			if (dirty & /*currentValidationState*/ 32) inputfield_changes.currentValidationState = /*currentValidationState*/ ctx[5];

			if (!updating_userdata && dirty & /*userData*/ 4) {
				updating_userdata = true;
				inputfield_changes.userdata = /*userData*/ ctx[2].password;
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_flush_callback"])(() => updating_userdata = false);
			}

			inputfield.$set(inputfield_changes);

			if (dirty & /*confirmation*/ 16) {
				input.checked = /*confirmation*/ ctx[4];
			}

			const button_changes = {};
			if (dirty & /*isRegButtonActive*/ 8) button_changes.disabled = !/*isRegButtonActive*/ ctx[3];
			button.$set(button_changes);
			if (updateInputs_action && Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["is_function"])(updateInputs_action.update) && dirty & /*typeOfLogin*/ 2) updateInputs_action.update.call(null, /*typeOfLogin*/ ctx[1]);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(inputfield.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(button.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_block0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_block1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(inputfield.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(button.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(form);
			if (if_block0) if_block0.d();
			if (if_block1) if_block1.d();
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(inputfield);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(button);
			mounted = false;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["run_all"])(dispose);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

const REDIRECT_URL_TO_SAVE_TOKEN_EZPROXY = "http://client.gpntbsib.ru:3002/savetoken?token=";

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("LoginForm", slots, []);
	let { typeOfLogin } = $$props;
	let { error } = $$props;
	let { signIn = false } = $$props;

	const userData = {
		email: "",
		libraryCardNumber: "",
		password: ""
	};

	let isRegButtonActive = false;
	let confirmation;
	let currentValidationState = _utils_validationState__WEBPACK_IMPORTED_MODULE_4__["validationState"];

	async function handleSubmit() {
		try {
			if (typeOfLogin == "email") {
				let res = await Object(_api_api__WEBPACK_IMPORTED_MODULE_1__["loginEmail"])({
					email: userData.email,
					password: userData.password
				});

				if (signIn) {
					if (res == "Wrong password" || !res) {
						throw new Error(res);
					}

					let url = REDIRECT_URL_TO_SAVE_TOKEN_EZPROXY + res.token;
					Object(_sapper_app__WEBPACK_IMPORTED_MODULE_6__["goto"])(url);
				} else {
					Object(_sapper_app__WEBPACK_IMPORTED_MODULE_6__["goto"])("/");
				}
			}

			if (typeOfLogin == "library-card") {
				console.log({
					libraryCardNumber: userData.libraryCardNumber,
					password: userData.password
				});

				let res = await Object(_api_api__WEBPACK_IMPORTED_MODULE_1__["loginLibraryCard"])({
					libraryCardNumber: userData.libraryCardNumber,
					password: userData.password
				});

				if (signIn) {
					if (res == "Wrong password" || !res) {
						throw new Error(res);
					}

					let url = REDIRECT_URL_TO_SAVE_TOKEN_EZPROXY + res.token;
					Object(_sapper_app__WEBPACK_IMPORTED_MODULE_6__["goto"])(url);
				} else {
					Object(_sapper_app__WEBPACK_IMPORTED_MODULE_6__["goto"])("/");
				}
			}
		} catch(e) {
			$$invalidate(0, error = "Неправильные почта или пароль");
			console.log(e);
		}
	}

	function updateInputs(node, bar) {
		clearInput();

		return {
			update(bar) {
				clearInput();
			}
		};
	}

	function clearInput() {
		for (let prop in userData) {
			$$invalidate(2, userData[prop] = "", userData);
		}

		for (let prop in currentValidationState) {
			$$invalidate(5, currentValidationState[prop] = { state: true, message: null }, currentValidationState);
		}
	}

	console.log(typeof clearInput);

	Object(svelte__WEBPACK_IMPORTED_MODULE_5__["afterUpdate"])(() => {
		for (let i in currentValidationState) {
			if (!currentValidationState[i].state) {
				$$invalidate(3, isRegButtonActive = false);
				return;
			}

			$$invalidate(3, isRegButtonActive = true);
		}
	}); /* for (let i in userData) {
  if (!userData[i]) {
    isRegButtonActive = false;
    return;
  }
  isRegButtonActive = true;
}*/ //console.log(validationState);

	Object(svelte__WEBPACK_IMPORTED_MODULE_5__["onDestroy"])(() => {
		clearInput();
	});

	const writable_props = ["typeOfLogin", "error", "signIn"];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console_1.warn(`<LoginForm> was created with unknown prop '${key}'`);
	});

	function inputfield_userdata_binding(value) {
		userData.email = value;
		$$invalidate(2, userData);
	}

	function inputfield_userdata_binding_1(value) {
		userData.libraryCardNumber = value;
		$$invalidate(2, userData);
	}

	function inputfield_userdata_binding_2(value) {
		userData.password = value;
		$$invalidate(2, userData);
	}

	function reset_handler(event) {
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["bubble"])($$self, event);
	}

	function input_change_handler() {
		confirmation = this.checked;
		$$invalidate(4, confirmation);
	}

	$$self.$$set = $$props => {
		if ("typeOfLogin" in $$props) $$invalidate(1, typeOfLogin = $$props.typeOfLogin);
		if ("error" in $$props) $$invalidate(0, error = $$props.error);
		if ("signIn" in $$props) $$invalidate(8, signIn = $$props.signIn);
	};

	$$self.$capture_state = () => ({
		loginEmail: _api_api__WEBPACK_IMPORTED_MODULE_1__["loginEmail"],
		loginLibraryCard: _api_api__WEBPACK_IMPORTED_MODULE_1__["loginLibraryCard"],
		signin: _api_api__WEBPACK_IMPORTED_MODULE_1__["signin"],
		signinLibraryCard: _api_api__WEBPACK_IMPORTED_MODULE_1__["signinLibraryCard"],
		Button: _Button_svelte__WEBPACK_IMPORTED_MODULE_2__["default"],
		validator: _utils_validator__WEBPACK_IMPORTED_MODULE_3__["validator"],
		validationState: _utils_validationState__WEBPACK_IMPORTED_MODULE_4__["validationState"],
		afterUpdate: svelte__WEBPACK_IMPORTED_MODULE_5__["afterUpdate"],
		onDestroy: svelte__WEBPACK_IMPORTED_MODULE_5__["onDestroy"],
		goto: _sapper_app__WEBPACK_IMPORTED_MODULE_6__["goto"],
		InputField: _InputField_svelte__WEBPACK_IMPORTED_MODULE_7__["default"],
		typeOfLogin,
		error,
		signIn,
		REDIRECT_URL_TO_SAVE_TOKEN_EZPROXY,
		userData,
		isRegButtonActive,
		confirmation,
		currentValidationState,
		handleSubmit,
		updateInputs,
		clearInput
	});

	$$self.$inject_state = $$props => {
		if ("typeOfLogin" in $$props) $$invalidate(1, typeOfLogin = $$props.typeOfLogin);
		if ("error" in $$props) $$invalidate(0, error = $$props.error);
		if ("signIn" in $$props) $$invalidate(8, signIn = $$props.signIn);
		if ("isRegButtonActive" in $$props) $$invalidate(3, isRegButtonActive = $$props.isRegButtonActive);
		if ("confirmation" in $$props) $$invalidate(4, confirmation = $$props.confirmation);
		if ("currentValidationState" in $$props) $$invalidate(5, currentValidationState = $$props.currentValidationState);
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	return [
		error,
		typeOfLogin,
		userData,
		isRegButtonActive,
		confirmation,
		currentValidationState,
		handleSubmit,
		updateInputs,
		signIn,
		inputfield_userdata_binding,
		inputfield_userdata_binding_1,
		inputfield_userdata_binding_2,
		reset_handler,
		input_change_handler
	];
}

class LoginForm extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-gqgwot-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], { typeOfLogin: 1, error: 0, signIn: 8 });

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "LoginForm",
			options,
			id: create_fragment.name
		});

		const { ctx } = this.$$;
		const props = options.props || {};

		if (/*typeOfLogin*/ ctx[1] === undefined && !("typeOfLogin" in props)) {
			console_1.warn("<LoginForm> was created without expected prop 'typeOfLogin'");
		}

		if (/*error*/ ctx[0] === undefined && !("error" in props)) {
			console_1.warn("<LoginForm> was created without expected prop 'error'");
		}
	}

	get typeOfLogin() {
		throw new Error_1("<LoginForm>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set typeOfLogin(value) {
		throw new Error_1("<LoginForm>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get error() {
		throw new Error_1("<LoginForm>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set error(value) {
		throw new Error_1("<LoginForm>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get signIn() {
		throw new Error_1("<LoginForm>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set signIn(value) {
		throw new Error_1("<LoginForm>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}
}

/* harmony default export */ __webpack_exports__["default"] = (LoginForm);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvY29tcG9uZW50cy9EaWdpdENvZGVJbnB1dC5zdmVsdGUiLCJ3ZWJwYWNrOi8vLy4vc3JjL2NvbXBvbmVudHMvTG9naW5Gb3JtLnN2ZWx0ZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Ozs7Ozs7O0FBQ2lEOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7aURBUXRDLEdBQUssSUFBQyxLQUFLOzs7Ozs7aURBVVgsR0FBSyxJQUFDLE1BQU07Ozs7OztpREFVWixHQUFLLElBQUMsS0FBSzs7Ozs7O2lEQVVYLEdBQUssSUFBQyxJQUFJOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3FGQTlCVixHQUFLLElBQUMsS0FBSzs7OztxRkFVWCxHQUFLLElBQUMsTUFBTTs7OztxRkFVWixHQUFLLElBQUMsS0FBSzs7OztxRkFVWCxHQUFLLElBQUMsSUFBSTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O09BckNiLFFBQVEsR0FBRyxvRUFBcUI7O09BRTNCLEtBQUs7RUFBSyxLQUFLLEVBQUUsRUFBRTtFQUFFLE1BQU0sRUFBRSxFQUFFO0VBQUUsS0FBSyxFQUFFLEVBQUU7RUFBRSxJQUFJLEVBQUUsRUFBRTs7Ozs7Ozs7O3VCQU1sRCxDQUFDO2tCQUNWLEtBQUssQ0FBQyxLQUFLLEdBQUcsQ0FBQyxDQUFDLE1BQU0sQ0FBQyxLQUFLOzs7eUJBU25CLENBQUM7a0JBQ1YsS0FBSyxDQUFDLE1BQU0sR0FBRyxDQUFDLENBQUMsTUFBTSxDQUFDLEtBQUs7Ozt5QkFTcEIsQ0FBQztrQkFDVixLQUFLLENBQUMsS0FBSyxHQUFHLENBQUMsQ0FBQyxNQUFNLENBQUMsS0FBSzs7O3lCQVNuQixDQUFDO2tCQUNWLEtBQUssQ0FBQyxJQUFJLEdBQUcsQ0FBQyxDQUFDLE1BQU0sQ0FBQyxLQUFLOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7QUNuQ1g7O0FBQ2lCO0FBQ1U7QUFDWTtBQUNYO0FBQ2I7QUFDVTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O2NBaUg3QixLQUFLOzs7Ozs7Ozs7a0JBREYsR0FBUSxJQUFDLEtBQUs7MkNBQWQsR0FBUSxJQUFDLEtBQUs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsrQ0FBZCxHQUFRLElBQUMsS0FBSzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O2NBYWpCLEtBQUs7Ozs7Ozs7OztrQkFERixHQUFRLElBQUMsaUJBQWlCOzJDQUExQixHQUFRLElBQUMsaUJBQWlCOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7K0NBQTFCLEdBQVEsSUFBQyxpQkFBaUI7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7aUNBZHhDLEdBQVcsT0FBSSxPQUFPO2lDQVl0QixHQUFXLE9BQUksY0FBYzs7Ozs7OztjQWdCcEIsS0FBSzs7dUJBRUQsSUFBSTtZQUNWLElBQUk7Ozs7Ozs7a0JBTEMsR0FBUSxJQUFDLFFBQVE7MkNBQWpCLEdBQVEsSUFBQyxRQUFROzs7Ozs7Ozs7cUNBd0JyQixHQUFpQjs7YUFFbkIsT0FBTzthQUNQLHdCQUF3Qjs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O29DQVhqQixHQUFZOzs7Ozs7Ozs7Ozs7Ozs7K0VBQ2YsT0FBTyxDQUFDLEdBQUcsa0JBQUMsR0FBWSxPQUF4QixPQUFPLENBQUMsR0FBRyxrQkFBQyxHQUFZOzs7Ozs7NkpBL0NyQixHQUFXO2lMQUNILEdBQVk7Ozs7Ozs7Ozt1QkFHakMsR0FBVyxPQUFJLE9BQU87Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3VCQVl0QixHQUFXLE9BQUksY0FBYzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsrQ0FjakIsR0FBUSxJQUFDLFFBQVE7Ozs7Ozs7cUNBZ0JoQixHQUFZOzs7O3lGQVFqQixHQUFpQjs7a05BdERaLEdBQVc7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztNQWxHdkIsa0NBQWtDLEdBQ3RDLGlEQUFpRDs7Ozs7T0FQeEMsV0FBVztPQUNYLEtBQUs7T0FDTCxNQUFNLEdBQUcsS0FBSzs7T0FPbkIsUUFBUTtFQUNaLEtBQUssRUFBRSxFQUFFO0VBQ1QsaUJBQWlCLEVBQUUsRUFBRTtFQUNyQixRQUFRLEVBQUUsRUFBRTs7O0tBRVYsaUJBQWlCLEdBQUcsS0FBSztLQUN6QixZQUFZO0tBRVosc0JBQXNCLEdBQUcsc0VBQWU7O2dCQUU3QixZQUFZOztPQUVuQixXQUFXLElBQUksT0FBTztRQUNwQixHQUFHLFNBQVMsMkRBQVU7S0FDeEIsS0FBSyxFQUFFLFFBQVEsQ0FBQyxLQUFLO0tBQ3JCLFFBQVEsRUFBRSxRQUFRLENBQUMsUUFBUTs7O1FBRXpCLE1BQU07U0FDSixHQUFHLElBQUksZ0JBQWdCLEtBQUssR0FBRztnQkFDdkIsS0FBSyxDQUFDLEdBQUc7OztTQUVqQixHQUFHLEdBQUcsa0NBQWtDLEdBQUcsR0FBRyxDQUFDLEtBQUs7S0FDeEQsd0RBQUksQ0FBQyxHQUFHOztLQUVSLHdEQUFJLENBQUMsR0FBRzs7OztPQUdSLFdBQVcsSUFBSSxjQUFjO0lBQy9CLE9BQU8sQ0FBQyxHQUFHO0tBQ1QsaUJBQWlCLEVBQUUsUUFBUSxDQUFDLGlCQUFpQjtLQUM3QyxRQUFRLEVBQUUsUUFBUSxDQUFDLFFBQVE7OztRQUV6QixHQUFHLFNBQVMsaUVBQWdCO0tBQzlCLGlCQUFpQixFQUFFLFFBQVEsQ0FBQyxpQkFBaUI7S0FDN0MsUUFBUSxFQUFFLFFBQVEsQ0FBQyxRQUFROzs7UUFFekIsTUFBTTtTQUNKLEdBQUcsSUFBSSxnQkFBZ0IsS0FBSyxHQUFHO2dCQUN2QixLQUFLLENBQUMsR0FBRzs7O1NBRWpCLEdBQUcsR0FBRyxrQ0FBa0MsR0FBRyxHQUFHLENBQUMsS0FBSztLQUN4RCx3REFBSSxDQUFDLEdBQUc7O0tBRVIsd0RBQUksQ0FBQyxHQUFHOzs7VUFHTCxDQUFDO21CQUNSLEtBQUssR0FBRywrQkFBK0I7R0FDdkMsT0FBTyxDQUFDLEdBQUcsQ0FBQyxDQUFDOzs7O1VBSVIsWUFBWSxDQUFDLElBQUksRUFBRSxHQUFHO0VBQzdCLFVBQVU7OztHQUVSLE1BQU0sQ0FBQyxHQUFHO0lBQ1IsVUFBVTs7Ozs7VUFJUCxVQUFVO1dBQ1IsSUFBSSxJQUFJLFFBQVE7bUJBQ3ZCLFFBQVEsQ0FBQyxJQUFJLElBQUksRUFBRTs7O1dBRVosSUFBSSxJQUFJLHNCQUFzQjttQkFDckMsc0JBQXNCLENBQUMsSUFBSSxNQUFNLEtBQUssRUFBRSxJQUFJLEVBQUUsT0FBTyxFQUFFLElBQUk7Ozs7Q0FJL0QsT0FBTyxDQUFDLEdBQUcsUUFBUSxVQUFVOztDQUM3QiwwREFBVztXQUNBLENBQUMsSUFBSSxzQkFBc0I7UUFDN0Isc0JBQXNCLENBQUMsQ0FBQyxFQUFFLEtBQUs7b0JBQ2xDLGlCQUFpQixHQUFHLEtBQUs7Ozs7bUJBRzNCLGlCQUFpQixHQUFHLElBQUk7Ozs7Ozs7Ozs7Q0FhNUIsd0RBQVM7RUFDUCxVQUFVOzs7Ozs7Ozs7O0VBV08sUUFBUSxDQUFDLEtBQUs7Ozs7O0VBWWQsUUFBUSxDQUFDLGlCQUFpQjs7Ozs7RUFZNUIsUUFBUSxDQUFDLFFBQVE7Ozs7Ozs7OztFQWdCaEIsWUFBWSIsImZpbGUiOiI0NGI1NjFjMzg5ZDJhZjdkYWQzOS9sb2dpbn5zaWduaW4ubG9naW5+c2lnbmluLmpzIiwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cclxuICBpbXBvcnQgeyBjcmVhdGVFdmVudERpc3BhdGNoZXIgfSBmcm9tIFwic3ZlbHRlXCI7XHJcbiAgY29uc3QgZGlzcGF0Y2ggPSBjcmVhdGVFdmVudERpc3BhdGNoZXIoKTtcclxuXHJcbiAgZXhwb3J0IGxldCB2YWx1ZSA9IHsgZmlyc3Q6IFwiXCIsIHNlY29uZDogXCJcIiwgdGhpcmQ6IFwiXCIsIGZvdXI6IFwiXCIgfTtcclxuPC9zY3JpcHQ+XHJcblxyXG48ZGl2IGNsYXNzPVwid3JhcHBlclwiPlxyXG4gIDxpbnB1dFxyXG4gICAgdmFsdWU9e3ZhbHVlLmZpcnN0fVxyXG4gICAgb246aW5wdXQ9eyhlKSA9PiB7XHJcbiAgICAgIHZhbHVlLmZpcnN0ID0gZS50YXJnZXQudmFsdWU7XHJcbiAgICB9fVxyXG4gICAgY2xhc3M9XCJkaWdpdC1jb2RlLWlucHV0XCJcclxuICAgIHBsYWNlaG9sZGVyPVwiKlwiXHJcbiAgICB0eXBlPVwidGV4dFwiXHJcbiAgICBtYXhsZW5ndGg9XCIxXCJcclxuICAvPlxyXG4gIDxpbnB1dFxyXG4gICAgdmFsdWU9e3ZhbHVlLnNlY29uZH1cclxuICAgIG9uOmlucHV0PXsoZSkgPT4ge1xyXG4gICAgICB2YWx1ZS5zZWNvbmQgPSBlLnRhcmdldC52YWx1ZTtcclxuICAgIH19XHJcbiAgICBjbGFzcz1cImRpZ2l0LWNvZGUtaW5wdXRcIlxyXG4gICAgcGxhY2Vob2xkZXI9XCIqXCJcclxuICAgIHR5cGU9XCJ0ZXh0XCJcclxuICAgIG1heGxlbmd0aD1cIjFcIlxyXG4gIC8+XHJcbiAgPGlucHV0XHJcbiAgICB2YWx1ZT17dmFsdWUudGhpcmR9XHJcbiAgICBvbjppbnB1dD17KGUpID0+IHtcclxuICAgICAgdmFsdWUudGhpcmQgPSBlLnRhcmdldC52YWx1ZTtcclxuICAgIH19XHJcbiAgICBjbGFzcz1cImRpZ2l0LWNvZGUtaW5wdXRcIlxyXG4gICAgcGxhY2Vob2xkZXI9XCIqXCJcclxuICAgIHR5cGU9XCJ0ZXh0XCJcclxuICAgIG1heGxlbmd0aD1cIjFcIlxyXG4gIC8+XHJcbiAgPGlucHV0XHJcbiAgICB2YWx1ZT17dmFsdWUuZm91cn1cclxuICAgIG9uOmlucHV0PXsoZSkgPT4ge1xyXG4gICAgICB2YWx1ZS5mb3VyID0gZS50YXJnZXQudmFsdWU7XHJcbiAgICB9fVxyXG4gICAgY2xhc3M9XCJkaWdpdC1jb2RlLWlucHV0XCJcclxuICAgIHBsYWNlaG9sZGVyPVwiKlwiXHJcbiAgICB0eXBlPVwidGV4dFwiXHJcbiAgICBtYXhsZW5ndGg9XCIxXCJcclxuICAvPlxyXG48L2Rpdj5cclxuXHJcbjxzdHlsZT5cclxuICAud3JhcHBlciB7XHJcbiAgICBkaXNwbGF5OiBmbGV4O1xyXG4gICAganVzdGlmeS1jb250ZW50OiBjZW50ZXI7XHJcbiAgICBhbGlnbi1pdGVtczogY2VudGVyO1xyXG4gIH1cclxuXHJcbiAgLmRpZ2l0LWNvZGUtaW5wdXQge1xyXG4gICAgd2lkdGg6IDYwcHg7XHJcbiAgICBoZWlnaHQ6IDYwcHg7XHJcbiAgICBib3JkZXI6IDJweCBzb2xpZCAjMDM1YmEwO1xyXG4gICAgYm9yZGVyLXJhZGl1czogMTBweDtcclxuICAgIGZvbnQtc3R5bGU6IG5vcm1hbDtcclxuICAgIGZvbnQtd2VpZ2h0OiAzMDA7XHJcbiAgICBmb250LXNpemU6IDE2cHg7XHJcbiAgICBsaW5lLWhlaWdodDogMTdweDtcclxuICAgIG91dGxpbmU6IG5vbmU7XHJcbiAgICBjb2xvcjogZ3JheTtcclxuICAgIGxldHRlci1zcGFjaW5nOiAwLjAyZW07XHJcbiAgICB0cmFuc2l0aW9uOiAwLjE1cyBlYXNlLW91dDtcclxuICAgIG1hcmdpbi1ib3R0b206IDIxcHg7XHJcbiAgICBwYWRkaW5nLWxlZnQ6IDIzcHg7XHJcbiAgICBtYXJnaW4tcmlnaHQ6IDIwcHg7XHJcbiAgfVxyXG4gIC5kaWdpdC1jb2RlLWlucHV0Omxhc3Qtb2YtdHlwZSB7XHJcbiAgICBtYXJnaW4tcmlnaHQ6IDA7XHJcbiAgfVxyXG48L3N0eWxlPlxyXG4iLCI8c2NyaXB0PlxuICBpbXBvcnQge1xuICAgIGxvZ2luRW1haWwsXG4gICAgbG9naW5MaWJyYXJ5Q2FyZCxcbiAgICBzaWduaW4sXG4gICAgc2lnbmluTGlicmFyeUNhcmQsXG4gIH0gZnJvbSBcIi4uL2FwaS9hcGlcIjtcbiAgaW1wb3J0IEJ1dHRvbiBmcm9tIFwiLi9CdXR0b24uc3ZlbHRlXCI7XG4gIGltcG9ydCB7IHZhbGlkYXRvciB9IGZyb20gXCIuLi91dGlscy92YWxpZGF0b3JcIjtcbiAgaW1wb3J0IHsgdmFsaWRhdGlvblN0YXRlIH0gZnJvbSBcIi4uL3V0aWxzL3ZhbGlkYXRpb25TdGF0ZVwiO1xuICBpbXBvcnQgeyBhZnRlclVwZGF0ZSwgb25EZXN0cm95IH0gZnJvbSBcInN2ZWx0ZVwiO1xuICBpbXBvcnQgeyBnb3RvIH0gZnJvbSBcIkBzYXBwZXIvYXBwXCI7XG4gIGltcG9ydCBJbnB1dEZpZWxkIGZyb20gXCIuL0lucHV0RmllbGQuc3ZlbHRlXCI7XG5cbiAgZXhwb3J0IGxldCB0eXBlT2ZMb2dpbjtcbiAgZXhwb3J0IGxldCBlcnJvcjtcbiAgZXhwb3J0IGxldCBzaWduSW4gPSBmYWxzZTtcbiAgLy9jb25zb2xlLmxvZyh2YWxpZGF0aW9uU3RhdGUpO1xuXG4gIFxuICBjb25zdCBSRURJUkVDVF9VUkxfVE9fU0FWRV9UT0tFTl9FWlBST1hZID1cbiAgICBcImh0dHA6Ly9jbGllbnQuZ3BudGJzaWIucnU6MzAwMi9zYXZldG9rZW4/dG9rZW49XCI7XG5cbiAgY29uc3QgdXNlckRhdGEgPSB7XG4gICAgZW1haWw6IFwiXCIsXG4gICAgbGlicmFyeUNhcmROdW1iZXI6IFwiXCIsXG4gICAgcGFzc3dvcmQ6IFwiXCIsXG4gIH07XG4gIGxldCBpc1JlZ0J1dHRvbkFjdGl2ZSA9IGZhbHNlO1xuICBsZXQgY29uZmlybWF0aW9uO1xuXG4gIGxldCBjdXJyZW50VmFsaWRhdGlvblN0YXRlID0gdmFsaWRhdGlvblN0YXRlO1xuXG4gIGFzeW5jIGZ1bmN0aW9uIGhhbmRsZVN1Ym1pdCgpIHtcbiAgICB0cnkge1xuICAgICAgaWYgKHR5cGVPZkxvZ2luID09IFwiZW1haWxcIikge1xuICAgICAgICBsZXQgcmVzID0gYXdhaXQgbG9naW5FbWFpbCh7XG4gICAgICAgICAgZW1haWw6IHVzZXJEYXRhLmVtYWlsLFxuICAgICAgICAgIHBhc3N3b3JkOiB1c2VyRGF0YS5wYXNzd29yZCxcbiAgICAgICAgfSk7XG4gICAgICAgIGlmIChzaWduSW4pIHtcbiAgICAgICAgICBpZiAocmVzID09IFwiV3JvbmcgcGFzc3dvcmRcIiB8fCAhcmVzKSB7XG4gICAgICAgICAgICB0aHJvdyBuZXcgRXJyb3IocmVzKTtcbiAgICAgICAgICB9XG4gICAgICAgICAgbGV0IHVybCA9IFJFRElSRUNUX1VSTF9UT19TQVZFX1RPS0VOX0VaUFJPWFkgKyByZXMudG9rZW47XG4gICAgICAgICAgZ290byh1cmwpO1xuICAgICAgICB9IGVsc2Uge1xuICAgICAgICAgIGdvdG8oXCIvXCIpO1xuICAgICAgICB9XG4gICAgICB9XG4gICAgICBpZiAodHlwZU9mTG9naW4gPT0gXCJsaWJyYXJ5LWNhcmRcIikge1xuICAgICAgICBjb25zb2xlLmxvZyh7XG4gICAgICAgICAgbGlicmFyeUNhcmROdW1iZXI6IHVzZXJEYXRhLmxpYnJhcnlDYXJkTnVtYmVyLFxuICAgICAgICAgIHBhc3N3b3JkOiB1c2VyRGF0YS5wYXNzd29yZCxcbiAgICAgICAgfSk7XG4gICAgICAgIGxldCByZXMgPSBhd2FpdCBsb2dpbkxpYnJhcnlDYXJkKHtcbiAgICAgICAgICBsaWJyYXJ5Q2FyZE51bWJlcjogdXNlckRhdGEubGlicmFyeUNhcmROdW1iZXIsXG4gICAgICAgICAgcGFzc3dvcmQ6IHVzZXJEYXRhLnBhc3N3b3JkLFxuICAgICAgICB9KTtcbiAgICAgICAgaWYgKHNpZ25Jbikge1xuICAgICAgICAgIGlmIChyZXMgPT0gXCJXcm9uZyBwYXNzd29yZFwiIHx8ICFyZXMpIHtcbiAgICAgICAgICAgIHRocm93IG5ldyBFcnJvcihyZXMpO1xuICAgICAgICAgIH1cbiAgICAgICAgICBsZXQgdXJsID0gUkVESVJFQ1RfVVJMX1RPX1NBVkVfVE9LRU5fRVpQUk9YWSArIHJlcy50b2tlbjtcbiAgICAgICAgICBnb3RvKHVybCk7XG4gICAgICAgIH0gZWxzZSB7XG4gICAgICAgICAgZ290byhcIi9cIik7XG4gICAgICAgIH1cbiAgICAgIH1cbiAgICB9IGNhdGNoIChlKSB7XG4gICAgICBlcnJvciA9IFwi0J3QtdC/0YDQsNCy0LjQu9GM0L3Ri9C1INC/0L7Rh9GC0LAg0LjQu9C4INC/0LDRgNC+0LvRjFwiO1xuICAgICAgY29uc29sZS5sb2coZSk7XG4gICAgICBcbiAgICB9XG4gIH1cbiAgZnVuY3Rpb24gdXBkYXRlSW5wdXRzKG5vZGUsIGJhcikge1xuICAgIGNsZWFySW5wdXQoKTtcbiAgICByZXR1cm4ge1xuICAgICAgdXBkYXRlKGJhcikge1xuICAgICAgICBjbGVhcklucHV0KCk7XG4gICAgICB9LFxuICAgIH07XG4gIH1cbiAgZnVuY3Rpb24gY2xlYXJJbnB1dCgpIHtcbiAgICBmb3IgKGxldCBwcm9wIGluIHVzZXJEYXRhKSB7XG4gICAgICB1c2VyRGF0YVtwcm9wXSA9IFwiXCI7XG4gICAgfVxuICAgIGZvciAobGV0IHByb3AgaW4gY3VycmVudFZhbGlkYXRpb25TdGF0ZSkge1xuICAgICAgY3VycmVudFZhbGlkYXRpb25TdGF0ZVtwcm9wXSA9IHsgc3RhdGU6IHRydWUsIG1lc3NhZ2U6IG51bGwgfTtcbiAgICB9XG4gIH1cblxuICBjb25zb2xlLmxvZyh0eXBlb2YgY2xlYXJJbnB1dCk7XG4gIGFmdGVyVXBkYXRlKCgpID0+IHtcbiAgICBmb3IgKGxldCBpIGluIGN1cnJlbnRWYWxpZGF0aW9uU3RhdGUpIHtcbiAgICAgIGlmICghY3VycmVudFZhbGlkYXRpb25TdGF0ZVtpXS5zdGF0ZSkge1xuICAgICAgICBpc1JlZ0J1dHRvbkFjdGl2ZSA9IGZhbHNlO1xuICAgICAgICByZXR1cm47XG4gICAgICB9XG4gICAgICBpc1JlZ0J1dHRvbkFjdGl2ZSA9IHRydWU7XG4gICAgfVxuXG4gICAgLyogZm9yIChsZXQgaSBpbiB1c2VyRGF0YSkge1xuICAgICAgaWYgKCF1c2VyRGF0YVtpXSkge1xuICAgICAgICBpc1JlZ0J1dHRvbkFjdGl2ZSA9IGZhbHNlO1xuICAgICAgICByZXR1cm47XG4gICAgICB9XG4gICAgICBpc1JlZ0J1dHRvbkFjdGl2ZSA9IHRydWU7XG4gICAgfSovXG5cbiAgICAvL2NvbnNvbGUubG9nKHZhbGlkYXRpb25TdGF0ZSk7XG4gIH0pO1xuICBvbkRlc3Ryb3koKCkgPT4ge1xuICAgIGNsZWFySW5wdXQoKTtcbiAgfSk7XG48L3NjcmlwdD5cblxuPGZvcm1cbiAgdXNlOnVwZGF0ZUlucHV0cz17dHlwZU9mTG9naW59XG4gIG9uOnN1Ym1pdHxwcmV2ZW50RGVmYXVsdD17aGFuZGxlU3VibWl0fVxuICBjbGFzcz1cInRleHQtbGVmdCBkLWZsZXggZmxleC1jb2x1bW4gYWxpZ24taXRlbXMtY2VudGVyIGxvZ2luLWZvcm1cIlxuPlxuICB7I2lmIHR5cGVPZkxvZ2luID09IFwiZW1haWxcIn1cbiAgICA8SW5wdXRGaWVsZFxuICAgICAgYmluZDp1c2VyZGF0YT17dXNlckRhdGEuZW1haWx9XG4gICAgICB2YWxpZGF0aW9uPXtmYWxzZX1cbiAgICAgIHtlcnJvcn1cbiAgICAgIGlkPVwiaW5wdXRFbWFpbFwiXG4gICAgICBuYW1lPVwiaW5wdXRFbWFpbFwiXG4gICAgICB0eXBlPVwiZW1haWxcIlxuICAgICAge2N1cnJlbnRWYWxpZGF0aW9uU3RhdGV9XG4gICAgICBsYWJlbFRleHQ9XCJFbWFpbFwiXG4gICAgLz5cbiAgey9pZn1cbiAgeyNpZiB0eXBlT2ZMb2dpbiA9PSBcImxpYnJhcnktY2FyZFwifVxuICAgIDxJbnB1dEZpZWxkXG4gICAgICBiaW5kOnVzZXJkYXRhPXt1c2VyRGF0YS5saWJyYXJ5Q2FyZE51bWJlcn1cbiAgICAgIHZhbGlkYXRpb249e2ZhbHNlfVxuICAgICAge2Vycm9yfVxuICAgICAgaWQ9XCJpbnB1dExpYnJhcnlDYXJkXCJcbiAgICAgIG5hbWU9XCJpbnB1dExpYnJhcnlDYXJkXCJcbiAgICAgIHR5cGU9XCJ0ZXh0XCJcbiAgICAgIHtjdXJyZW50VmFsaWRhdGlvblN0YXRlfVxuICAgICAgbGFiZWxUZXh0PVwi0J3QvtC80LXRgCDRh9C40YLQsNGC0LXQu9GM0YHQutC+0LPQviDQsdC40LvQtdGC0LBcIlxuICAgIC8+XG4gIHsvaWZ9XG5cbiAgPElucHV0RmllbGRcbiAgICBiaW5kOnVzZXJkYXRhPXt1c2VyRGF0YS5wYXNzd29yZH1cbiAgICBvbjpyZXNldFxuICAgIHZhbGlkYXRpb249e2ZhbHNlfVxuICAgIGlkPVwiaW5wdXRQYXNzd29yZFwiXG4gICAgcmVzZXRQYXNzd29yZD1cInt0cnVlfTtcIlxuICAgIHBhc3N3b3JkPXt0cnVlfVxuICAgIG5hbWU9XCJpbnB1dFBhc3N3b3JkXCJcbiAgICB0eXBlPVwicGFzc3dvcmRcIlxuICAgIHtjdXJyZW50VmFsaWRhdGlvblN0YXRlfVxuICAgIGxhYmVsVGV4dD1cItCf0LDRgNC+0LvRjFwiXG4gIC8+XG4gIDxkaXYgY2xhc3M9XCJkLWZsZXggZmxleC1yb3cganVzdGlmeS1jb250ZW50LWNlbnRlciBhbGlnbi1pdGVtcy1jZW50ZXJcIj5cbiAgICA8aW5wdXRcbiAgICAgIGNsYXNzPVwiXCJcbiAgICAgIGlkPVwiY29uZmlybWF0aW9uXCJcbiAgICAgIHR5cGU9XCJjaGVja2JveFwiXG4gICAgICBiaW5kOmNoZWNrZWQ9e2NvbmZpcm1hdGlvbn1cbiAgICAgIG9uOmNoYW5nZT17Y29uc29sZS5sb2coY29uZmlybWF0aW9uKX1cbiAgICAvPlxuICAgIDxsYWJlbCBjbGFzcz1cImQtcHItY29uZmlybS1sYWJlbFwiIGZvcj1cImNvbmZpcm1hdGlvblwiPlxuICAgICAg0JfQsNC/0L7QvNC90LjRgtGMINC80LXQvdGPXG4gICAgPC9sYWJlbD5cbiAgPC9kaXY+XG4gIDxCdXR0b25cbiAgICBkaXNhYmxlZD17IWlzUmVnQnV0dG9uQWN0aXZlfVxuICAgIHR5cGU9XCJzdWJtaXRcIlxuICAgIGNvbnRlbnQ9e1wi0JLQvtC50YLQuFwifVxuICAgIGNsYXNzZXM9e1wibS1idXR0b25fbWFyZ2luLWJvdHRvbVwifVxuICAvPlxuICA8IS0tPGJ1dHRvbiBvbjpjbGljaz17Y2xlYXJJbnB1dH0gY2xhc3M9XCJjbGVhci1idXR0b25cIiB0eXBlPVwiYnV0dG9uXCJcbiAgICA+0KHQsdGA0L7RgdC40YLRjCDQstGB0LU8L2J1dHRvblxuICA+LS0+XG48L2Zvcm0+XG5cbjxzdHlsZT5cbiAgLmxvZ2luLWZvcm0ge1xuICAgIG1hcmdpbjogMTQwcHggMCAwIDA7XG4gIH1cblxuICAubS1idXR0b24ge1xuICAgIGJvcmRlcjogbm9uZTtcbiAgICBjb2xvcjogd2hpdGU7XG4gICAgd2lkdGg6IDIwMHB4O1xuICAgIGhlaWdodDogNDBweDtcbiAgICBiYWNrZ3JvdW5kLWNvbG9yOiAjMDM1YmEwO1xuICAgIGJvcmRlci1yYWRpdXM6IDEwcHg7XG4gICAgZm9udC1zdHlsZTogbm9ybWFsO1xuICAgIGZvbnQtd2VpZ2h0OiBib2xkO1xuICAgIGZvbnQtc2l6ZTogMjBweDtcbiAgICBsaW5lLWhlaWdodDogMjJweDtcbiAgfVxuXG4gIC5sb2ctYnV0dG9uOmRpc2FibGVkIHtcbiAgICBiYWNrZ3JvdW5kLWNvbG9yOiBncmF5O1xuICB9XG4gIC5sb2ctYnV0dG9uIHtcbiAgICBtYXJnaW4tdG9wOiAzNnB4O1xuICB9XG5cbiAgLmNsZWFyLWJ1dHRvbiB7XG4gICAgYm9yZGVyOiBub25lO1xuICAgIHBvc2l0aW9uOiBhYnNvbHV0ZTtcbiAgICBib3R0b206IDIwcHg7XG4gICAgcmlnaHQ6IDIwcHg7XG4gICAgZm9udC1zdHlsZTogbm9ybWFsO1xuICAgIGZvbnQtd2VpZ2h0OiAzMDA7XG4gICAgZm9udC1zaXplOiAxMnB4O1xuICAgIGxpbmUtaGVpZ2h0OiAxM3B4O1xuICAgIHRleHQtYWxpZ246IGNlbnRlcjtcbiAgICBsZXR0ZXItc3BhY2luZzogMC4wMmVtO1xuICAgIGJhY2tncm91bmQtY29sb3I6IHRyYW5zcGFyZW50O1xuICB9XG5cbiAgLmQtcHItY29uZmlybS1sYWJlbCB7XG4gICAgbWFyZ2luOiAwIDAgMCAxM3B4O1xuICAgIGZvbnQtc3R5bGU6IG5vcm1hbDtcbiAgICBmb250LXdlaWdodDogMzAwO1xuICAgIGZvbnQtc2l6ZTogMTJweDtcbiAgICBsaW5lLWhlaWdodDogMTNweDtcbiAgfVxuXG4gIEBtZWRpYSBzY3JlZW4gYW5kIChtYXgtd2lkdGg6IDcyMHB4KSB7XG4gICAgLmxvZ2luLWZvcm0ge1xuICAgICAgbWFyZ2luOiA0MHB4IDAgMCAwO1xuICAgIH1cbiAgfVxuPC9zdHlsZT5cbiJdLCJzb3VyY2VSb290IjoiIn0=