/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};
/******/
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/
/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId]) {
/******/ 			return installedModules[moduleId].exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			i: moduleId,
/******/ 			l: false,
/******/ 			exports: {}
/******/ 		};
/******/
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
/******/
/******/ 		// Flag the module as loaded
/******/ 		module.l = true;
/******/
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/
/******/
/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;
/******/
/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;
/******/
/******/ 	// define getter function for harmony exports
/******/ 	__webpack_require__.d = function(exports, name, getter) {
/******/ 		if(!__webpack_require__.o(exports, name)) {
/******/ 			Object.defineProperty(exports, name, { enumerable: true, get: getter });
/******/ 		}
/******/ 	};
/******/
/******/ 	// define __esModule on exports
/******/ 	__webpack_require__.r = function(exports) {
/******/ 		if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
/******/ 			Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
/******/ 		}
/******/ 		Object.defineProperty(exports, '__esModule', { value: true });
/******/ 	};
/******/
/******/ 	// create a fake namespace object
/******/ 	// mode & 1: value is a module id, require it
/******/ 	// mode & 2: merge all properties of value into the ns
/******/ 	// mode & 4: return value when already ns object
/******/ 	// mode & 8|1: behave like require
/******/ 	__webpack_require__.t = function(value, mode) {
/******/ 		if(mode & 1) value = __webpack_require__(value);
/******/ 		if(mode & 8) return value;
/******/ 		if((mode & 4) && typeof value === 'object' && value && value.__esModule) return value;
/******/ 		var ns = Object.create(null);
/******/ 		__webpack_require__.r(ns);
/******/ 		Object.defineProperty(ns, 'default', { enumerable: true, value: value });
/******/ 		if(mode & 2 && typeof value != 'string') for(var key in value) __webpack_require__.d(ns, key, function(key) { return value[key]; }.bind(null, key));
/******/ 		return ns;
/******/ 	};
/******/
/******/ 	// getDefaultExport function for compatibility with non-harmony modules
/******/ 	__webpack_require__.n = function(module) {
/******/ 		var getter = module && module.__esModule ?
/******/ 			function getDefault() { return module['default']; } :
/******/ 			function getModuleExports() { return module; };
/******/ 		__webpack_require__.d(getter, 'a', getter);
/******/ 		return getter;
/******/ 	};
/******/
/******/ 	// Object.prototype.hasOwnProperty.call
/******/ 	__webpack_require__.o = function(object, property) { return Object.prototype.hasOwnProperty.call(object, property); };
/******/
/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";
/******/
/******/
/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(__webpack_require__.s = "./src/service-worker.js");
/******/ })
/************************************************************************/
/******/ ({

/***/ "./src/node_modules/@sapper/service-worker.js":
/*!****************************************************!*\
  !*** ./src/node_modules/@sapper/service-worker.js ***!
  \****************************************************/
/*! exports provided: timestamp, files, assets, shell, routes */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"timestamp\", function() { return timestamp; });\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"files\", function() { return files; });\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"assets\", function() { return files; });\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"shell\", function() { return shell; });\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"routes\", function() { return routes; });\n// This file is generated by Sapper — do not edit it!\nconst timestamp = 1624004159725;\n\nconst files = [\n\t\"/service-worker-index.html\",\n\t\"/global.css\",\n\t\"/images/1619403630042.jpg\",\n\t\"/images/1619403790334.jpg\",\n\t\"/images/1619403964495.jpg\",\n\t\"/images/1619404234180.jpg\",\n\t\"/images/1619408036630.jpg\",\n\t\"/images/1619408121189.jpg\",\n\t\"/images/1619409153094.jpg\",\n\t\"/images/1619409225924.jpg\",\n\t\"/images/1619576701818.jpg\",\n\t\"/images/1619677112185.jpg\",\n\t\"/images/1621664612705.jpg\",\n\t\"/images/Add.svg\",\n\t\"/images/admin/3User.svg\",\n\t\"/images/admin/buttonOther.svg\",\n\t\"/images/admin/buttonOtherWhite.svg\",\n\t\"/images/admin/button_user_account_call.svg\",\n\t\"/images/admin/button_user_account_message.svg\",\n\t\"/images/admin/button_user_account_other.svg\",\n\t\"/images/admin/Caretdown.svg\",\n\t\"/images/admin/close.svg\",\n\t\"/images/admin/EditSquare.svg\",\n\t\"/images/admin/Home.svg\",\n\t\"/images/admin/InfoCircle.svg\",\n\t\"/images/admin/Logout.svg\",\n\t\"/images/admin/Profile.svg\",\n\t\"/images/admin/Search.svg\",\n\t\"/images/admin/Setting.svg\",\n\t\"/images/admin/status_valid.svg\",\n\t\"/images/admin/Work.svg\",\n\t\"/images/book.svg\",\n\t\"/images/burger-menu.svg\",\n\t\"/images/cancel-save-photo.svg\",\n\t\"/images/Cancel.svg\",\n\t\"/images/circles.svg\",\n\t\"/images/Cross.svg\",\n\t\"/images/Edit.svg\",\n\t\"/images/exit.svg\",\n\t\"/images/Eye.svg\",\n\t\"/images/favicon.png\",\n\t\"/images/fb-blue.svg\",\n\t\"/images/fb.svg\",\n\t\"/images/google-symbol.svg\",\n\t\"/images/google.svg\",\n\t\"/images/gosuslugi.png\",\n\t\"/images/library.jpg\",\n\t\"/images/library.png\",\n\t\"/images/location.svg\",\n\t\"/images/lock.svg\",\n\t\"/images/logo-192.png\",\n\t\"/images/logo-512.png\",\n\t\"/images/logo.svg\",\n\t\"/images/logo_2.png\",\n\t\"/images/notification.svg\",\n\t\"/images/orcid-blue.svg\",\n\t\"/images/orcid.svg\",\n\t\"/images/photo-1521996319423-90475f382dff.jfif\",\n\t\"/images/photo-1617301949085-788b443ec77e.jfif\",\n\t\"/images/pointer.svg\",\n\t\"/images/profile.png\",\n\t\"/images/rating.svg\",\n\t\"/images/save-photo.svg\",\n\t\"/images/search.svg\",\n\t\"/images/vk-blue.svg\",\n\t\"/images/vk.svg\",\n\t\"/manifest.json\",\n\t\"/vendor/bloggersans/BloggerSans-Bold.otf\",\n\t\"/vendor/bloggersans/BloggerSans-BoldItalic.otf\",\n\t\"/vendor/bloggersans/BloggerSans-Italic.otf\",\n\t\"/vendor/bloggersans/BloggerSans-Light.otf\",\n\t\"/vendor/bloggersans/BloggerSans-LightItalic.otf\",\n\t\"/vendor/bloggersans/BloggerSans-Medium.otf\",\n\t\"/vendor/bloggersans/BloggerSans-MediumItalic.otf\",\n\t\"/vendor/bloggersans/bloggersans.css\",\n\t\"/vendor/bloggersans/BloggerSans.otf\",\n\t\"/vendor/GothamPro/GothamPro.css\",\n\t\"/vendor/GothamPro/GothamProBlack/GothamProBlack.eot\",\n\t\"/vendor/GothamPro/GothamProBlack/GothamProBlack.ttf\",\n\t\"/vendor/GothamPro/GothamProBlack/GothamProBlack.woff\",\n\t\"/vendor/GothamPro/GothamProBlackItalic/GothamProBlackItalic.eot\",\n\t\"/vendor/GothamPro/GothamProBlackItalic/GothamProBlackItalic.ttf\",\n\t\"/vendor/GothamPro/GothamProBlackItalic/GothamProBlackItalic.woff\",\n\t\"/vendor/GothamPro/GothamProBold/GothamProBold.eot\",\n\t\"/vendor/GothamPro/GothamProBold/GothamProBold.ttf\",\n\t\"/vendor/GothamPro/GothamProBold/GothamProBold.woff\",\n\t\"/vendor/GothamPro/GothamProBoldItalic/GothamProBoldItalic.eot\",\n\t\"/vendor/GothamPro/GothamProBoldItalic/GothamProBoldItalic.ttf\",\n\t\"/vendor/GothamPro/GothamProBoldItalic/GothamProBoldItalic.woff\",\n\t\"/vendor/GothamPro/GothamProItalic/GothamProItalic.eot\",\n\t\"/vendor/GothamPro/GothamProItalic/GothamProItalic.ttf\",\n\t\"/vendor/GothamPro/GothamProItalic/GothamProItalic.woff\",\n\t\"/vendor/GothamPro/GothamProLight/GothamProLight.eot\",\n\t\"/vendor/GothamPro/GothamProLight/GothamProLight.ttf\",\n\t\"/vendor/GothamPro/GothamProLight/GothamProLight.woff\",\n\t\"/vendor/GothamPro/GothamProLightItalic/GothamProLightItalic.eot\",\n\t\"/vendor/GothamPro/GothamProLightItalic/GothamProLightItalic.ttf\",\n\t\"/vendor/GothamPro/GothamProLightItalic/GothamProLightItalic.woff\",\n\t\"/vendor/GothamPro/GothamProMedium/GothamProMedium.eot\",\n\t\"/vendor/GothamPro/GothamProMedium/GothamProMedium.ttf\",\n\t\"/vendor/GothamPro/GothamProMedium/GothamProMedium.woff\",\n\t\"/vendor/GothamPro/GothamProMediumItalic/GothamProMediumItalic.eot\",\n\t\"/vendor/GothamPro/GothamProMediumItalic/GothamProMediumItalic.ttf\",\n\t\"/vendor/GothamPro/GothamProMediumItalic/GothamProMediumItalic.woff\",\n\t\"/vendor/GothamPro/GothamProRegular/GothamProRegular.eot\",\n\t\"/vendor/GothamPro/GothamProRegular/GothamProRegular.ttf\",\n\t\"/vendor/GothamPro/GothamProRegular/GothamProRegular.woff\"\n];\n // legacy\n\nconst shell = [\n\t\"/client/04a600d2d011e7ffa5e2/0.0.js\",\n\t\"/client/04a600d2d011e7ffa5e2/admin.admin.js\",\n\t\"/client/04a600d2d011e7ffa5e2/admin~index.admin~index.js\",\n\t\"/client/04a600d2d011e7ffa5e2/admin~index~login~signin~signup.admin~index~login~signin~signup.js\",\n\t\"/client/04a600d2d011e7ffa5e2/blog.blog.js\",\n\t\"/client/04a600d2d011e7ffa5e2/blog_$slug.blog_$slug.js\",\n\t\"/client/04a600d2d011e7ffa5e2/index.index.js\",\n\t\"/client/04a600d2d011e7ffa5e2/index~login~signin~signup.index~login~signin~signup.js\",\n\t\"/client/04a600d2d011e7ffa5e2/login.login.js\",\n\t\"/client/04a600d2d011e7ffa5e2/login~signin.login~signin.js\",\n\t\"/client/04a600d2d011e7ffa5e2/login~signin~signup.login~signin~signup.js\",\n\t\"/client/04a600d2d011e7ffa5e2/main.js\",\n\t\"/client/04a600d2d011e7ffa5e2/profile_$slug.profile_$slug.js\",\n\t\"/client/04a600d2d011e7ffa5e2/signin.signin.js\",\n\t\"/client/04a600d2d011e7ffa5e2/signup.signup.js\",\n\t\"/client/04a600d2d011e7ffa5e2/vendors~admin~signup.vendors~admin~signup.js\"\n];\n\nconst routes = [\n\t{ pattern: /^\\/$/ },\n\t{ pattern: /^\\/profile\\/([^/]+?)\\/?$/ },\n\t{ pattern: /^\\/signin\\/?$/ },\n\t{ pattern: /^\\/signup\\/?$/ },\n\t{ pattern: /^\\/admin\\/?$/ },\n\t{ pattern: /^\\/login\\/?$/ },\n\t{ pattern: /^\\/blog\\/?$/ },\n\t{ pattern: /^\\/blog\\/([^/]+?)\\/?$/ }\n];\n\n//# sourceURL=webpack:///./src/node_modules/@sapper/service-worker.js?");

/***/ }),

/***/ "./src/service-worker.js":
/*!*******************************!*\
  !*** ./src/service-worker.js ***!
  \*******************************/
/*! no exports provided */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _sapper_service_worker__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! @sapper/service-worker */ \"./src/node_modules/@sapper/service-worker.js\");\n\n\nconst ASSETS = `cache${_sapper_service_worker__WEBPACK_IMPORTED_MODULE_0__[\"timestamp\"]}`;\n\n// `shell` is an array of all the files generated by the bundler,\n// `files` is an array of everything in the `static` directory\nconst to_cache = _sapper_service_worker__WEBPACK_IMPORTED_MODULE_0__[\"shell\"].concat(_sapper_service_worker__WEBPACK_IMPORTED_MODULE_0__[\"files\"]);\nconst staticAssets = new Set(to_cache);\n\nself.addEventListener('install', event => {\n\tevent.waitUntil(\n\t\tcaches\n\t\t\t.open(ASSETS)\n\t\t\t.then(cache => cache.addAll(to_cache))\n\t\t\t.then(() => {\n\t\t\t\tself.skipWaiting();\n\t\t\t})\n\t);\n});\n\nself.addEventListener('activate', event => {\n\tevent.waitUntil(\n\t\tcaches.keys().then(async keys => {\n\t\t\t// delete old caches\n\t\t\tfor (const key of keys) {\n\t\t\t\tif (key !== ASSETS) await caches.delete(key);\n\t\t\t}\n\n\t\t\tself.clients.claim();\n\t\t})\n\t);\n});\n\n\n/**\n * Fetch the asset from the network and store it in the cache. \n * Fall back to the cache if the user is offline.\n */\nasync function fetchAndCache(request) {\n\tconst cache = await caches.open(`offline${_sapper_service_worker__WEBPACK_IMPORTED_MODULE_0__[\"timestamp\"]}`)\n\n\ttry {\n\t\tconst response = await fetch(request);\n\t\tcache.put(request, response.clone());\n\t\treturn response;\n\t} catch (err) {\n\t\tconst response = await cache.match(request);\n\t\tif (response) return response;\n\n\t\tthrow err;\n\t}\n}\n\nself.addEventListener('fetch', event => {\n\tif (event.request.method !== 'GET' || event.request.headers.has('range')) return;\n\n\tconst url = new URL(event.request.url);\n\n\t// don't try to handle e.g. data: URIs\n\tconst isHttp = url.protocol.startsWith('http');\n\tconst isDevServerRequest = url.hostname === self.location.hostname && url.port !== self.location.port;\n\tconst isStaticAsset = url.host === self.location.host && staticAssets.has(url.pathname);\n\tconst skipBecauseUncached = event.request.cache === 'only-if-cached' && !isStaticAsset;\n\n\tif (isHttp && !isDevServerRequest && !skipBecauseUncached) {\n\t\tevent.respondWith(\n\t\t\t(async () => {\n\t\t\t\t// always serve static files and bundler-generated assets from cache.\n\t\t\t\t// if your application has other URLs with data that will never change,\n\t\t\t\t// set this variable to true for them and they will only be fetched once.\n\t\t\t\tconst cachedAsset = isStaticAsset && await caches.match(event.request);\n\n\t\t\t\t// for pages, you might want to serve a shell `service-worker-index.html` file,\n\t\t\t\t// which Sapper has generated for you. It's not right for every\n\t\t\t\t// app, but if it's right for yours then uncomment this section\n\t\t\t\t/*\n\t\t\t\tif (!cachedAsset && url.origin === self.origin && routes.find(route => route.pattern.test(url.pathname))) {\n\t\t\t\t\treturn caches.match('/service-worker-index.html');\n\t\t\t\t}\n\t\t\t\t*/\n\n\t\t\t\treturn cachedAsset || fetchAndCache(event.request);\n\t\t\t})()\n\t\t);\n\t}\n});\n\n\n//# sourceURL=webpack:///./src/service-worker.js?");

/***/ })

/******/ });